"""
Thrust Vector Control (TVC) Plant Dynamics

This module implements the rigid-body dynamics for a single-axis TVC system.
The dynamics are formulated in the affine-in-control form ẋ = f(x) + g(x)u
to enable CLF-CBF QP construction.

Author: Generated by GitHub Copilot
"""

import numpy as np
from typing import Tuple, Optional
from dataclasses import dataclass


@dataclass
class TVCParameters:
    """Physical parameters for the TVC plant"""
    # Vehicle properties
    mass: float = 1.0  # kg
    moment_of_inertia: float = 0.1  # kg⋅m²
    length: float = 1.0  # m (distance from CoM to thruster)
    
    # Thrust properties
    nominal_thrust: float = 15.0  # N (1.5x weight for hover margin)
    max_thrust: float = 20.0  # N
    min_thrust: float = 5.0  # N
    
    # Actuator limits
    max_gimbal_angle: float = np.pi/6  # ±30 degrees
    max_gimbal_rate: float = np.pi  # rad/s
    
    # Environment
    gravity: float = 9.81  # m/s²
    
    # Safety margins
    max_angle: float = np.pi/4  # ±45 degrees
    max_angular_rate: float = 2*np.pi  # rad/s
    
    # Disturbances
    disturbance_torque_std: float = 0.1  # N⋅m
    sensor_noise_std: float = 0.01  # rad, rad/s


class TVCPlant:
    """
    Single-axis TVC plant with rigid-body dynamics.
    
    State: x = [θ, θ̇] where θ is attitude angle, θ̇ is angular rate
    Control: u = δ (gimbal angle)
    
    Dynamics: ẋ = f(x) + g(x)u + d(t)
    where d(t) represents disturbances
    """
    
    def __init__(self, params: Optional[TVCParameters] = None):
        self.params = params or TVCParameters()
        self.reset()
        
    def reset(self, initial_state: Optional[np.ndarray] = None):
        """Reset the plant to initial conditions"""
        if initial_state is not None:
            self.state = initial_state.copy()
        else:
            # Small random initial perturbation
            self.state = np.array([
                np.random.normal(0, 0.1),  # θ
                np.random.normal(0, 0.1)   # θ̇
            ])
        
        self.time = 0.0
        self.thrust = self.params.nominal_thrust
        
    def set_thrust(self, thrust: float):
        """Set the current thrust level"""
        self.thrust = np.clip(thrust, self.params.min_thrust, self.params.max_thrust)
        
    def f(self, x: np.ndarray) -> np.ndarray:
        """Drift dynamics f(x)"""
        theta, theta_dot = x
        
        # Gravitational torque (stabilizing for small angles)
        # For upright configuration, gravity provides restoring torque
        gravity_torque = -self.params.mass * self.params.gravity * self.params.length * np.sin(theta)
        
        return np.array([
            theta_dot,
            gravity_torque / self.params.moment_of_inertia
        ])
    
    def g(self, x: np.ndarray) -> np.ndarray:
        """Control input matrix g(x)"""
        # Thrust vector control provides torque proportional to thrust and gimbal angle
        control_authority = self.thrust * self.params.length / self.params.moment_of_inertia
        
        return np.array([
            0.0,
            control_authority
        ])
    
    def step(self, control: float, dt: float = 0.01, add_disturbance: bool = True) -> np.ndarray:
        """
        Integrate the dynamics forward by one time step
        
        Args:
            control: Gimbal angle (rad)
            dt: Time step (s)
            add_disturbance: Whether to add process noise
            
        Returns:
            New state [θ, θ̇]
        """
        # Clip control input
        u = np.clip(control, -self.params.max_gimbal_angle, self.params.max_gimbal_angle)
        
        # Compute dynamics
        f_x = self.f(self.state)
        g_x = self.g(self.state)
        
        # Disturbance torque
        disturbance = np.array([0.0, 0.0])
        if add_disturbance:
            disturbance[1] = np.random.normal(0, self.params.disturbance_torque_std) / self.params.moment_of_inertia
        
        # Euler integration (for simplicity; could use RK4)
        state_dot = f_x + g_x * u + disturbance
        self.state = self.state + state_dot * dt
        self.time += dt
        
        return self.get_observation()
    
    def get_observation(self, add_noise: bool = True) -> np.ndarray:
        """
        Get current state observation with optional sensor noise
        
        Returns:
            Observed state [θ, θ̇] with noise
        """
        obs = self.state.copy()
        
        if add_noise:
            noise = np.random.normal(0, self.params.sensor_noise_std, 2)
            obs += noise
            
        return obs
    
    def get_linearization(self, x_eq: np.ndarray, u_eq: float) -> Tuple[np.ndarray, np.ndarray]:
        """
        Get linearized dynamics around equilibrium point
        
        Args:
            x_eq: Equilibrium state
            u_eq: Equilibrium control
            
        Returns:
            A, B matrices for linear system dx = Ax + Bu
        """
        # For this simple system, we can compute analytically
        theta_eq, _ = x_eq
        
        # A matrix (Jacobian of f+gu w.r.t. x)
        A = np.array([
            [0.0, 1.0],
            [-self.params.mass * self.params.gravity * self.params.length * np.cos(theta_eq) / self.params.moment_of_inertia, 0.0]
        ])
        
        # B matrix (g(x))
        B = self.g(x_eq).reshape(-1, 1)
        
        return A, B
    
    def is_safe(self) -> bool:
        """Check if current state satisfies safety constraints"""
        theta, theta_dot = self.state
        
        angle_safe = abs(theta) <= self.params.max_angle
        rate_safe = abs(theta_dot) <= self.params.max_angular_rate
        
        return angle_safe and rate_safe
    
    def get_safety_margins(self) -> dict:
        """Get current safety margins for all constraints"""
        theta, theta_dot = self.state
        
        return {
            'angle_margin': self.params.max_angle - abs(theta),
            'rate_margin': self.params.max_angular_rate - abs(theta_dot)
        }


class TVCActuator:
    """
    TVC gimbal actuator model with rate and position limits
    """
    
    def __init__(self, params: Optional[TVCParameters] = None):
        self.params = params or TVCParameters()
        self.reset()
        
    def reset(self):
        """Reset actuator state"""
        self.position = 0.0  # Current gimbal angle
        self.velocity = 0.0  # Current gimbal rate
        
    def step(self, command: float, dt: float = 0.01) -> float:
        """
        Step the actuator dynamics with rate limiting
        
        Args:
            command: Desired gimbal angle
            dt: Time step
            
        Returns:
            Actual gimbal angle
        """
        # Clip command to position limits
        command = np.clip(command, -self.params.max_gimbal_angle, self.params.max_gimbal_angle)
        
        # Compute desired velocity
        desired_velocity = (command - self.position) / dt
        
        # Rate limit the velocity
        self.velocity = np.clip(desired_velocity, -self.params.max_gimbal_rate, self.params.max_gimbal_rate)
        
        # Update position
        self.position += self.velocity * dt
        
        # Final position clipping (safety)
        self.position = np.clip(self.position, -self.params.max_gimbal_angle, self.params.max_gimbal_angle)
        
        return self.position


def test_plant():
    """Test the TVC plant implementation"""
    plant = TVCPlant()
    actuator = TVCActuator()
    
    print("Testing TVC Plant Dynamics")
    print("=" * 40)
    
    # Test equilibrium point
    plant.reset(np.array([0.0, 0.0]))
    print(f"Initial state: {plant.state}")
    print(f"f(0): {plant.f(plant.state)}")
    print(f"g(0): {plant.g(plant.state)}")
    
    # Test linearization
    A, B = plant.get_linearization(np.array([0.0, 0.0]), 0.0)
    print(f"\nLinearization at hover:")
    print(f"A = \n{A}")
    print(f"B = \n{B}")
    
    # Simulate a step response
    print("\nStep response simulation:")
    plant.reset(np.array([0.1, 0.0]))  # 0.1 rad initial angle
    
    for i in range(100):
        # Simple proportional control
        u_cmd = -2.0 * plant.state[0]  # P gain = 2
        u_actual = actuator.step(u_cmd)
        state = plant.step(u_actual, add_disturbance=False)
        
        if i % 20 == 0:
            print(f"t={i*0.01:.2f}s: θ={state[0]:.3f}, θ̇={state[1]:.3f}, u={u_actual:.3f}")
    
    print(f"\nSafety status: {plant.is_safe()}")
    print(f"Safety margins: {plant.get_safety_margins()}")