"""
Linear Quadratic Regulator (LQR) Controller for TVC System

This module implements the LQR baseline controller that provides:
1. Stabilizing feedback control around hover equilibrium
2. Lyapunov function for CLF-CBF QP safety filter
3. Reference tracking capabilities

Author: Generated by GitHub Copilot
"""

import numpy as np
import scipy.linalg
from typing import Optional, Tuple
from dataclasses import dataclass

from ..dynamics import TVCPlant, TVCParameters


@dataclass
class LQRParameters:
    """LQR controller tuning parameters"""
    # State weights [θ, θ̇]
    Q: np.ndarray = None
    
    # Control weight
    R: float = 1.0
    
    # CLF constraint parameter
    clg_gamma: float = 1.0  # Exponential decay rate for CLF
    
    def __post_init__(self):
        if self.Q is None:
            # Default state weights: penalize angle more than rate
            self.Q = np.diag([100.0, 10.0])  # [θ penalty, θ̇ penalty]


class LQRController:
    """
    LQR controller for TVC system with CLF functionality
    
    Provides:
    - Stabilizing feedback: u = -K @ x
    - Lyapunov function: V(x) = x^T @ P @ x
    - CLF constraint computation for safety filter
    """
    
    def __init__(self, plant: TVCPlant, lqr_params: Optional[LQRParameters] = None):
        self.plant = plant
        self.params = lqr_params or LQRParameters()
        
        # Compute LQR gain and Lyapunov matrix
        self._compute_lqr_gain()
        
    def _compute_lqr_gain(self):
        """Compute LQR gain matrix and Lyapunov function"""
        # Get linearization around hover equilibrium
        x_eq = np.array([0.0, 0.0])  # Upright hover
        u_eq = 0.0  # No gimbal deflection at hover
        
        A, B = self.plant.get_linearization(x_eq, u_eq)
        
        # Solve continuous-time algebraic Riccati equation
        self.P = scipy.linalg.solve_continuous_are(A, B, self.params.Q, np.array([[self.params.R]]))
        
        # Compute LQR gain: K = R^(-1) B^T P
        self.K = (1.0 / self.params.R) * B.T @ self.P
        self.K = self.K.flatten()  # Make it 1D for easier use
        
        # Store system matrices
        self.A = A
        self.B = B
        
        print(f"LQR Controller Initialized:")
        print(f"K = {self.K}")
        print(f"P = \n{self.P}")
        
    def control(self, state: np.ndarray, reference: np.ndarray = None) -> float:
        """
        Compute LQR control action
        
        Args:
            state: Current state [θ, θ̇]
            reference: Reference state (default: [0, 0])
            
        Returns:
            Control action (gimbal angle)
        """
        if reference is None:
            reference = np.array([0.0, 0.0])
            
        error = state - reference
        return -np.dot(self.K, error)
    
    def lyapunov_function(self, state: np.ndarray, reference: np.ndarray = None) -> float:
        """
        Compute Lyapunov function value V(x) = x^T P x
        
        Args:
            state: Current state
            reference: Reference state (default: [0, 0])
            
        Returns:
            Lyapunov function value
        """
        if reference is None:
            reference = np.array([0.0, 0.0])
            
        error = state - reference
        return error.T @ self.P @ error
    
    def lyapunov_derivative(self, state: np.ndarray, control: float, reference: np.ndarray = None) -> float:
        """
        Compute Lyapunov function derivative: dV/dt = ∇V^T (f + gu)
        
        Args:
            state: Current state
            control: Control input
            reference: Reference state (default: [0, 0])
            
        Returns:
            Lyapunov derivative
        """
        if reference is None:
            reference = np.array([0.0, 0.0])
            
        error = state - reference
        
        # Gradient of V: ∇V = 2Px
        grad_V = 2 * self.P @ error
        
        # System dynamics
        f_x = self.plant.f(state)
        g_x = self.plant.g(state)
        
        # dV/dt = ∇V^T (f + gu)
        return grad_V.T @ (f_x + g_x * control)
    
    def clf_constraint_coefficients(self, state: np.ndarray, reference: np.ndarray = None) -> Tuple[float, float, float]:
        """
        Compute CLF constraint coefficients for QP: L_f V + L_g V * u + γV ≤ δ
        
        Args:
            state: Current state
            reference: Reference state (default: [0, 0])
            
        Returns:
            (L_f V, L_g V, γV) where constraint is: L_f V + L_g V * u + γV ≤ δ
        """
        if reference is None:
            reference = np.array([0.0, 0.0])
            
        error = state - reference
        
        # Gradient of V: ∇V = 2Px
        grad_V = 2 * self.P @ error
        
        # System dynamics
        f_x = self.plant.f(state)
        g_x = self.plant.g(state)
        
        # Lie derivatives
        L_f_V = grad_V.T @ f_x
        L_g_V = grad_V.T @ g_x
        
        # V(x)
        V_x = self.lyapunov_function(state, reference)
        
        return L_f_V, L_g_V, self.params.clg_gamma * V_x
    
    def is_stable_with_lqr(self, state: np.ndarray, reference: np.ndarray = None) -> bool:
        """
        Check if LQR control would be stabilizing (V̇ < 0)
        
        Args:
            state: Current state
            reference: Reference state
            
        Returns:
            True if LQR is stabilizing
        """
        u_lqr = self.control(state, reference)
        V_dot = self.lyapunov_derivative(state, u_lqr, reference)
        return V_dot < 0
    
    def get_reachable_set_estimate(self, max_lyapunov_value: float) -> dict:
        """
        Estimate reachable set based on Lyapunov level sets
        
        Args:
            max_lyapunov_value: Maximum allowed Lyapunov function value
            
        Returns:
            Dictionary with estimated bounds
        """
        # For quadratic Lyapunov function V = x^T P x ≤ c
        # the level set is an ellipse with semi-axes related to eigenvalues of P
        
        eigenvals, eigenvecs = np.linalg.eig(self.P)
        
        # Semi-axes of ellipse: sqrt(c/λ_i)
        semi_axes = np.sqrt(max_lyapunov_value / eigenvals)
        
        return {
            'max_angle': semi_axes[0] if eigenvals[0] > eigenvals[1] else semi_axes[1],
            'max_rate': semi_axes[1] if eigenvals[0] > eigenvals[1] else semi_axes[0],
            'eigenvalues': eigenvals,
            'eigenvectors': eigenvecs
        }


def test_lqr_controller():
    """Test the LQR controller implementation"""
    from ..dynamics import TVCParameters
    
    print("Testing LQR Controller")
    print("=" * 40)
    
    # Create plant and controller
    params = TVCParameters()
    plant = TVCPlant(params)
    
    # Custom LQR parameters
    lqr_params = LQRParameters(
        Q=np.diag([50.0, 1.0]),  # Heavy penalty on angle
        R=1.0,
        clg_gamma=2.0
    )
    
    controller = LQRController(plant, lqr_params)
    
    # Test control computation
    test_state = np.array([0.1, 0.05])  # 0.1 rad angle, 0.05 rad/s rate
    u_lqr = controller.control(test_state)
    print(f"Test state: {test_state}")
    print(f"LQR control: {u_lqr:.4f}")
    
    # Test Lyapunov function
    V = controller.lyapunov_function(test_state)
    print(f"Lyapunov value: {V:.4f}")
    
    # Test CLF constraint
    L_f_V, L_g_V, gamma_V = controller.clf_constraint_coefficients(test_state)
    print(f"CLF coefficients: L_f V={L_f_V:.4f}, L_g V={L_g_V:.4f}, γV={gamma_V:.4f}")
    
    # Test stability
    V_dot = controller.lyapunov_derivative(test_state, u_lqr)
    print(f"Lyapunov derivative with LQR: {V_dot:.4f} (should be negative)")
    print(f"LQR is stabilizing: {controller.is_stable_with_lqr(test_state)}")
    
    # Test reachable set estimation
    reachable = controller.get_reachable_set_estimate(1.0)
    print(f"Reachable set (V≤1.0): angle={reachable['max_angle']:.3f}, rate={reachable['max_rate']:.3f}")
    
    # Simulate closed-loop response
    print("\nClosed-loop simulation:")
    plant.reset(np.array([0.2, 0.1]))  # Larger initial disturbance
    
    for i in range(50):
        state = plant.get_observation(add_noise=False)
        u = controller.control(state)
        plant.step(u, add_disturbance=False)
        
        if i % 10 == 0:
            V = controller.lyapunov_function(state)
            print(f"t={i*0.01:.2f}s: θ={state[0]:.3f}, θ̇={state[1]:.3f}, u={u:.3f}, V={V:.3f}")


if __name__ == "__main__":
    test_lqr_controller()