"""
Model Predictive Control (MPC) for TVC System

This controller computes control inputs by solving a finite-horizon QP
at each time step on the linearized discrete-time dynamics around hover.

It also exposes CLF-related utilities (Lyapunov function and its derivatives)
based on the continuous-time algebraic Riccati equation so it can be used
with the existing CLF-CBF safety filter as a drop-in replacement for LQR.

Author: Generated by GitHub Copilot
"""

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np
import scipy.linalg
import cvxpy as cp

from ..dynamics import TVCPlant


@dataclass
class MPCParameters:
    """MPC tuning parameters"""
    Q: Optional[np.ndarray] = None  # State weight (2x2)
    R: float = 1.0                  # Control weight (scalar)
    N: int = 20                     # Horizon length (steps)
    dt: float = 0.01                # Discretization timestep
    du_rate_limit: bool = True      # Enforce rate limit on u
    warm_start: bool = True         # Warm start optimizer
    terminal_lqr: bool = True       # Use LQR terminal cost

    def __post_init__(self):
        if self.Q is None:
            self.Q = np.diag([100.0, 10.0])


class MPCController:
    """
    Linear MPC controller using cvxpy (OSQP) for the TVC system.

    Exposes the same interface as LQRController used elsewhere:
    - control(state, reference)
    - lyapunov_function(state, reference)
    - lyapunov_derivative(state, control, reference)
    - clf_constraint_coefficients(state, reference)
    """

    def __init__(self, plant: TVCPlant, mpc_params: Optional[MPCParameters] = None):
        self.plant = plant
        self.params = mpc_params or MPCParameters()

        # Linearize around hover equilibrium and discretize
        x_eq = np.array([0.0, 0.0])
        u_eq = 0.0
        A_c, B_c = self.plant.get_linearization(x_eq, u_eq)
        self.Ad, self.Bd = self._c2d(A_c, B_c, self.params.dt)

        # Terminal cost via continuous-time ARE (common in MPC)
        self.P = scipy.linalg.solve_continuous_are(A_c, B_c, self.params.Q, np.array([[self.params.R]]))

        # Pre-allocate cvxpy variables and parameters
        n_x = 2
        n_u = 1
        N = self.params.N

        self.x_var = cp.Variable((n_x, N + 1))
        self.u_var = cp.Variable((n_u, N))
        self.x0_par = cp.Parameter(n_x)
        self.ref_par = cp.Parameter(n_x)

        # Build objective and constraints (time-invariant, parameterized by x0, ref)
        cost = 0
        constr = []
        constr.append(self.x_var[:, 0] == self.x0_par)

        # Limits
        u_max = float(self.plant.params.max_gimbal_angle)
        du_max = float(self.plant.params.max_gimbal_rate * self.params.dt)

        for k in range(N):
            # Stage cost
            xk = self.x_var[:, k]
            uk = self.u_var[:, k]
            cost += cp.quad_form(xk - self.ref_par, self.params.Q) + self.params.R * cp.sum_squares(uk)

            # Dynamics
            constr.append(self.x_var[:, k + 1] == self.Ad @ xk + self.Bd.flatten() * uk)

            # Input constraints
            constr += [cp.abs(uk) <= u_max]

            # Rate constraints (on delta-u)
            if self.params.du_rate_limit:
                if k == 0:
                    # approximate last u as current actuator position (plant doesn't expose; assume last_u=0)
                    # Better: track last command; we store internally and update each call
                    pass
                else:
                    constr += [cp.abs(self.u_var[:, k] - self.u_var[:, k - 1]) <= du_max]

        # Terminal cost
        if self.params.terminal_lqr:
            cost += cp.quad_form(self.x_var[:, N] - self.ref_par, self.P)

        self.problem = cp.Problem(cp.Minimize(cost), constr)

        # Internal last command for rate constraint warm start approximation
        self._last_u: float = 0.0

        # Configure solver options
        self._solve_kwargs = dict(solver=cp.OSQP, warm_start=self.params.warm_start, verbose=False)

    @staticmethod
    def _c2d(A: np.ndarray, B: np.ndarray, dt: float) -> Tuple[np.ndarray, np.ndarray]:
        """Zero-order hold discretization."""
        n = A.shape[0]
        M = np.block([[A, B], [np.zeros((1, n + 1))]])
        Md = scipy.linalg.expm(M * dt)
        Ad = Md[:n, :n]
        Bd = Md[:n, n:]
        return Ad, Bd

    def control(self, state: np.ndarray, reference: Optional[np.ndarray] = None) -> float:
        """Compute MPC control action (first input of optimal sequence)."""
        if reference is None:
            reference = np.zeros(2)

        # Set parameters
        self.x0_par.value = np.asarray(state).flatten()
        self.ref_par.value = np.asarray(reference).flatten()

        # Add first-step rate constraint to last_u via temporary constraint if enabled
        # We emulate du limit by adjusting bounds through an extra constraint for k=0
        extra_constr = []
        if self.params.du_rate_limit:
            du_max = float(self.plant.params.max_gimbal_rate * self.params.dt)
            extra_constr.append(cp.abs(self.u_var[:, 0] - self._last_u) <= du_max)

        # Temporarily extend problem with extra constraints
        try:
            if extra_constr:
                temp_prob = cp.Problem(self.problem.objective, self.problem.constraints + extra_constr)
                temp_prob.solve(**self._solve_kwargs)
                prob = temp_prob
            else:
                self.problem.solve(**self._solve_kwargs)
                prob = self.problem
        except Exception as e:
            # Fallback: simple PD if QP fails
            theta, theta_dot = state
            u = float(-2.0 * theta - 0.5 * theta_dot)
            return float(np.clip(u, -self.plant.params.max_gimbal_angle, self.plant.params.max_gimbal_angle))

        if prob.status not in (cp.OPTIMAL, cp.OPTIMAL_INACCURATE):
            theta, theta_dot = state
            u = float(-2.0 * theta - 0.5 * theta_dot)
            return float(np.clip(u, -self.plant.params.max_gimbal_angle, self.plant.params.max_gimbal_angle))

        u_val = self.u_var[:, 0].value
        if u_val is None:
            # Fallback PD if solver didn't return a value
            theta, theta_dot = state
            u = float(-2.0 * theta - 0.5 * theta_dot)
            return float(np.clip(u, -self.plant.params.max_gimbal_angle, self.plant.params.max_gimbal_angle))
        u0 = float(np.asarray(u_val).ravel()[0])
        self._last_u = u0
        return u0

    # --------- CLF utilities for safety filter compatibility ---------
    def lyapunov_function(self, state: np.ndarray, reference: np.ndarray | None = None) -> float:
        if reference is None:
            reference = np.zeros(2)
        e = np.asarray(state).flatten() - np.asarray(reference).flatten()
        return float(e.T @ self.P @ e)

    def lyapunov_derivative(self, state: np.ndarray, control: float, reference: np.ndarray | None = None) -> float:
        if reference is None:
            reference = np.zeros(2)
        e = np.asarray(state).flatten() - np.asarray(reference).flatten()
        grad_V = 2 * self.P @ e
        f_x = self.plant.f(np.asarray(state).flatten())
        g_x = self.plant.g(np.asarray(state).flatten())
        return float(grad_V.T @ (f_x + g_x * control))

    def clf_constraint_coefficients(self, state: np.ndarray, reference: np.ndarray | None = None) -> Tuple[float, float, float]:
        if reference is None:
            reference = np.zeros(2)
        e = np.asarray(state).flatten() - np.asarray(reference).flatten()
        grad_V = 2 * self.P @ e
        f_x = self.plant.f(np.asarray(state).flatten())
        g_x = self.plant.g(np.asarray(state).flatten())
        L_f_V = float(grad_V.T @ f_x)
        L_g_V = float(grad_V.T @ g_x)
        # Use same gamma convention as LQRParameters.clg_gamma default if available
        gamma = 1.0
        V_x = float(e.T @ self.P @ e)
        return L_f_V, L_g_V, gamma * V_x
