"""
Control Barrier Function (CBF) and Control Lyapunov Function (CLF) 
Quadratic Programming (QP) Safety Filter

This module implements the safety-critical control framework that guarantees:
1. Forward invariance of safe sets through CBF constraints
2. Stability through CLF constraints (soft)
3. Real-time QP solving with OSQP

Mathematical formulation:
minimize_{u,δ} (1/2)||u - u_des||² + ρδ²
subject to:
  - CLF: L_f V + L_g V * u + γV ≤ δ  (soft stability)
  - CBF: L_f h + L_g h * u ≥ -α(h)    (hard safety)
  - Actuator: u_min ≤ u ≤ u_max         (hard limits)

Author: Generated by GitHub Copilot
"""

import numpy as np
import osqp
import scipy.sparse as sparse
from typing import Optional, List, Tuple, Dict
from dataclasses import dataclass

from ..dynamics import TVCPlant, TVCParameters


@dataclass 
class SafetyParameters:
    """Parameters for CBF-QP safety filter"""
    # CBF parameters
    angle_cbf_alpha: float = 2.0  # Class-K function parameter for angle constraint
    rate_cbf_alpha: float = 1.5   # Class-K function parameter for rate constraint
    
    # CLF parameters
    clf_penalty: float = 1000.0   # Weight on CLF slack variable δ
    
    # QP solver parameters
    qp_eps_abs: float = 1e-4
    qp_eps_rel: float = 1e-4
    qp_max_iter: int = 1000
    qp_verbose: bool = False
    
    # Safety margins (percentage of actual limits)
    angle_margin_factor: float = 0.9  # Use 90% of actual angle limit
    rate_margin_factor: float = 0.9   # Use 90% of actual rate limit


class CBFBarrier:
    """
    Control Barrier Function implementation
    
    For constraint h(x) ≥ 0, enforces:
    L_f h(x) + L_g h(x) * u ≥ -α(h(x))
    
    where α(·) is a class-K function (α(s) = αs for linear case)
    """
    
    def __init__(self, name: str, alpha: float):
        self.name = name
        self.alpha = alpha  # Class-K function parameter
        
    def barrier_function(self, state: np.ndarray, params: TVCParameters) -> float:
        """Compute barrier function value h(x)"""
        raise NotImplementedError
        
    def barrier_jacobian(self, state: np.ndarray, params: TVCParameters) -> np.ndarray:
        """Compute gradient ∇h(x)"""
        raise NotImplementedError
        
    def cbf_constraint_coefficients(self, state: np.ndarray, plant: TVCPlant) -> Tuple[float, float, float]:
        """
        Compute CBF constraint coefficients: L_f h + L_g h * u ≥ -α(h)
        
        Returns:
            (L_f h, L_g h, -α(h)) where constraint is: L_f h + L_g h * u ≥ b
        """
        h_val = self.barrier_function(state, plant.params)
        grad_h = self.barrier_jacobian(state, plant.params)
        
        # System dynamics
        f_x = plant.f(state) 
        g_x = plant.g(state)
        
        # Lie derivatives
        L_f_h = float(grad_h.T @ f_x)
        L_g_h = float(grad_h.T @ g_x)
        
        # Class-K function: α(h) = α * h (could be more complex)
        alpha_h = self.alpha * h_val
        
        return L_f_h, L_g_h, -alpha_h


class AngleCBF(CBFBarrier):
    """CBF for angle constraint: |θ| ≤ θ_max"""
    
    def __init__(self, alpha: float, margin_factor: float = 0.9):
        super().__init__("angle_cbf", alpha)
        self.margin_factor = margin_factor
        
    def barrier_function(self, state: np.ndarray, params: TVCParameters) -> float:
        """h(x) = θ_max² - θ² (always positive when safe)"""
        theta = state[0]
        theta_max = params.max_angle * self.margin_factor
        return theta_max**2 - theta**2
        
    def barrier_jacobian(self, state: np.ndarray, params: TVCParameters) -> np.ndarray:
        """∇h = [-2θ, 0]"""
        theta = state[0]
        return np.array([-2*theta, 0.0])


class RateCBF(CBFBarrier):
    """CBF for angular rate constraint: |θ̇| ≤ θ̇_max"""
    
    def __init__(self, alpha: float, margin_factor: float = 0.9):
        super().__init__("rate_cbf", alpha)
        self.margin_factor = margin_factor
        
    def barrier_function(self, state: np.ndarray, params: TVCParameters) -> float:
        """h(x) = θ̇_max² - θ̇²"""
        theta_dot = state[1]
        theta_dot_max = params.max_angular_rate * self.margin_factor
        return theta_dot_max**2 - theta_dot**2
        
    def barrier_jacobian(self, state: np.ndarray, params: TVCParameters) -> np.ndarray:
        """∇h = [0, -2θ̇]"""
        theta_dot = state[1]
        return np.array([0.0, -2*theta_dot])


class CLFCBFQPFilter:
    """
    CLF-CBF Quadratic Programming Safety Filter
    
    Solves the optimization problem:
    minimize_{u,δ} (1/2)||u - u_des||² + ρδ²
    subject to:
      - CLF: L_f V + L_g V * u + γV ≤ δ
      - CBF: L_f h_i + L_g h_i * u ≥ -α_i(h_i) for all i
      - u_min ≤ u ≤ u_max
    """
    
    def __init__(self, 
                 plant: TVCPlant,
                 stabilizing_controller,
                 safety_params: Optional[SafetyParameters] = None):
        
        self.plant = plant
        # Controller must provide clf_constraint_coefficients(state, reference)
        # and control(state, reference)
        self.lqr = stabilizing_controller
        self.params = safety_params or SafetyParameters()
        
        # Initialize barrier functions
        self.barriers = [
            AngleCBF(self.params.angle_cbf_alpha, self.params.angle_margin_factor),
            RateCBF(self.params.rate_cbf_alpha, self.params.rate_margin_factor)
        ]
        
        # QP solver will be created fresh for each solve
        self.qp_solver = None
        self.slack_penalty = self.params.clf_penalty
        
        # Diagnostics
        self.solve_stats = {
            'total_solves': 0,
            'infeasible_count': 0,
            'avg_solve_time': 0.0,
            'last_status': None
        }
        
    def filter_control(self, desired_control: float, state: np.ndarray, 
                      reference: Optional[np.ndarray] = None, warm_start: bool = True) -> Dict:
        """
        Filter the desired control through CLF-CBF QP
        
        Args:
            desired_control: Desired control input (e.g., from learning policy)
            state: Current system state
            reference: Reference state for CLF
            warm_start: Use warm starting for faster solves
            
        Returns:
            Dictionary with filtered control and solve information
        """
        self.solve_stats['total_solves'] += 1
        
        # Build QP problem
        success = self._build_qp_problem(desired_control, state, reference)
        
        if not success:
            return {
                'control': desired_control,  # Return desired if QP setup failed
                'slack': 0.0,
                'feasible': False,
                'solve_time': 0.0,
                'status': 'setup_failed',
                'barrier_values': self._get_barrier_values(state),
                'intervention': False
            }
        
        # Solve QP
        if self.qp_solver is None:
            return {
                'control': desired_control,
                'slack': 0.0,
                'feasible': False,
                'solve_time': 0.0,
                'status': 'solver_unavailable',
                'barrier_values': self._get_barrier_values(state),
                'intervention': False,
                'desired_control': desired_control,
            }
        result = self.qp_solver.solve()
        
        # Extract solution
        if result.x is not None and len(result.x) >= 2:
            u_filtered = result.x[0]
            slack = result.x[1]
            feasible = result.info.status in ['solved', 'solved_inaccurate']
        else:
            u_filtered = desired_control
            slack = 0.0
            feasible = False
            
        # Update statistics
        self.solve_stats['last_status'] = result.info.status
        if not feasible:
            self.solve_stats['infeasible_count'] += 1
            
        # Detect intervention (when filtered differs significantly from desired)
        intervention = abs(u_filtered - desired_control) > 0.01  # 1% threshold
        
        return {
            'control': u_filtered,
            'slack': slack,
            'feasible': feasible,
            'solve_time': result.info.solve_time if hasattr(result.info, 'solve_time') else 0.0,
            'status': result.info.status,
            'barrier_values': self._get_barrier_values(state),
            'intervention': intervention,
            'desired_control': desired_control
        }
    
    def _build_qp_problem(self, u_des: float, state: np.ndarray, reference: Optional[np.ndarray] = None) -> bool:
        """Build QP matrices for current state"""
        try:
            # Linear cost: q = [-u_des, 0] for minimizing (u-u_des)²/2 + ρδ²/2
            q = np.array([-u_des, 0.0])
            
            # Constraint matrix A and bounds l, u
            constraints = []
            l_bounds = []
            u_bounds = []
            
            # 1. CLF constraint: L_f V + L_g V * u + γV ≤ δ
            #    Rearranged: L_g V * u - δ ≤ -(L_f V + γV)
            # Ensure reference is an ndarray: if None, use current state as reference
            ref = reference if reference is not None else state
            L_f_V, L_g_V, gamma_V = self.lqr.clf_constraint_coefficients(state, ref)
            constraints.append([L_g_V, -1.0])  # [L_g V, -1] * [u, δ]
            l_bounds.append(-np.inf)
            u_bounds.append(-(L_f_V + gamma_V))
            
            # 2. CBF constraints: L_f h + L_g h * u ≥ -α(h)
            #    Rearranged: L_g h * u ≥ -(L_f h + α(h))
            for barrier in self.barriers:
                L_f_h, L_g_h, neg_alpha_h = barrier.cbf_constraint_coefficients(state, self.plant)
                constraints.append([L_g_h, 0.0])  # [L_g h, 0] * [u, δ]
                l_bounds.append(-(L_f_h - neg_alpha_h))  # Note: neg_alpha_h is already negative
                u_bounds.append(np.inf)
            
            # 3. Actuator bounds: u_min ≤ u ≤ u_max
            constraints.append([1.0, 0.0])  # u bound
            l_bounds.append(-self.plant.params.max_gimbal_angle)
            u_bounds.append(self.plant.params.max_gimbal_angle)
            
            # 4. Slack bounds: δ ≥ 0
            constraints.append([0.0, 1.0])  # δ bound  
            l_bounds.append(0.0)
            u_bounds.append(np.inf)
            
            # Convert to sparse matrix
            A = sparse.csc_matrix(constraints)
            l = np.array(l_bounds)
            u = np.array(u_bounds)
            
            # Recreate QP solver with new problem (safer than updating)
            self.qp_solver = osqp.OSQP()
            
            # Setup QP problem
            # Quadratic cost matrix P = diag([1, ρ]) for minimizing (u-u_des)²/2 + ρδ²/2
            P = sparse.diags([1.0, self.slack_penalty], format='csc')
            
            self.qp_solver.setup(P=P, q=q, A=A, l=l, u=u, 
                               verbose=False, eps_abs=1e-6, eps_rel=1e-6)
            
            return True
            
        except Exception as e:
            print(f"QP setup failed: {e}")
            return False
    
    def _get_barrier_values(self, state: np.ndarray) -> Dict[str, float]:
        """Get current barrier function values for diagnostics"""
        values = {}
        for barrier in self.barriers:
            values[barrier.name] = barrier.barrier_function(state, self.plant.params)
        return values
    
    def is_safe(self, state: np.ndarray) -> bool:
        """Check if current state satisfies all safety constraints"""
        barrier_values = self._get_barrier_values(state)
        return all(h >= 0 for h in barrier_values.values())
    
    def get_diagnostics(self) -> Dict:
        """Get solver diagnostics and statistics"""
        total_solves = self.solve_stats['total_solves']
        
        return {
            'total_solves': total_solves,
            'infeasible_rate': self.solve_stats['infeasible_count'] / max(total_solves, 1),
            'last_status': self.solve_stats['last_status'],
            'barriers': [b.name for b in self.barriers]
        }
    
    def __getstate__(self):
        """Custom serialization for multiprocessing compatibility"""
        # Save all essential state except the non-pickable QP solver
        state = self.__dict__.copy()
        # Remove the unpicklable QP solver
        del state['qp_solver']
        return state
    
    def __setstate__(self, state):
        """Custom deserialization for multiprocessing compatibility"""
        # Restore the object state
        self.__dict__.update(state)
        # QP solver will be created fresh when needed
        self.qp_solver = None


def test_cbf_qp_filter():
    """Test the CBF-QP safety filter"""
    from ..dynamics import TVCParameters
    
    print("Testing CBF-QP Safety Filter")
    print("=" * 50)
    
    # Create system components
    params = TVCParameters()
    plant = TVCPlant(params)
    from .mpc import MPCController
    lqr = MPCController(plant)
    
    safety_params = SafetyParameters(
        angle_cbf_alpha=3.0,
        rate_cbf_alpha=2.0,
        clf_penalty=100.0
    )
    
    safety_filter = CLFCBFQPFilter(plant, lqr, safety_params)
    
    # Test 1: Safe state with LQR control
    print("\n1. Testing safe state with MPC control:")
    safe_state = np.array([0.1, 0.05])  # Small angle and rate
    u_lqr = lqr.control(safe_state)
    
    result = safety_filter.filter_control(u_lqr, safe_state)
    print(f"State: {safe_state}")
    print(f"Baseline control: {u_lqr:.4f}")
    print(f"Filtered control: {result['control']:.4f}")
    print(f"Slack: {result['slack']:.4f}")
    print(f"Feasible: {result['feasible']}")
    print(f"Intervention: {result['intervention']}")
    print(f"Barrier values: {result['barrier_values']}")
    
    # Test 2: Near-unsafe state
    print("\n2. Testing near-unsafe state:")
    unsafe_state = np.array([0.6, 3.0])  # Large angle and rate
    u_aggressive = 2.0  # Aggressive control that might violate constraints
    
    result = safety_filter.filter_control(u_aggressive, unsafe_state)
    print(f"State: {unsafe_state}")
    print(f"Desired control: {u_aggressive:.4f}")
    print(f"Filtered control: {result['control']:.4f}")
    print(f"Slack: {result['slack']:.4f}")
    print(f"Feasible: {result['feasible']}")
    print(f"Intervention: {result['intervention']}")
    print(f"Barrier values: {result['barrier_values']}")
    
    # Test 3: Closed-loop simulation with safety filter
    print("\n3. Closed-loop simulation with safety filter:")
    plant.reset(np.array([0.5, 0.2]))  # Start near constraint boundary
    
    for i in range(20):
        state = plant.get_observation(add_noise=False)
        
        # Use LQR as desired control
        u_des = lqr.control(state)
        
        # Apply safety filter
        result = safety_filter.filter_control(u_des, state)
        u_safe = result['control']
        
        # Apply to plant
        plant.step(u_safe, add_disturbance=False)
        
        if i % 5 == 0:
            barrier_vals = result['barrier_values']
            print(f"t={i*0.01:.2f}s: θ={state[0]:.3f}, θ̇={state[1]:.3f}, "
                  f"u_des={u_des:.3f}, u_safe={u_safe:.3f}, "
                  f"intervention={result['intervention']}")
            print(f"  Barriers: angle={barrier_vals['angle_cbf']:.3f}, rate={barrier_vals['rate_cbf']:.3f}")
    
    # Print final diagnostics
    print(f"\nFinal diagnostics: {safety_filter.get_diagnostics()}")


if __name__ == "__main__":
    test_cbf_qp_filter()