"""
Neuro-Evolutionary Training for TVC Control

This module implements the evolutionary algorithm described in the TVC video:
1. Population of 1000 neural networks with random initialization
2. Fitness evaluation based on angular error and motor jerk
3. Selection of best performers
4. Generation of next population through mutation and crossover
5. Evolution over many generations until convergence

The approach trains networks to map [thrust, angle, angular_velocity] → gimbal_angle
as shown in the video demonstration.

Author: Generated by GitHub Copilot
"""

import numpy as np
import torch
import matplotlib.pyplot as plt
from typing import List, Tuple, Dict, Optional, Callable
import random
from dataclasses import dataclass
from concurrent.futures import ProcessPoolExecutor
import multiprocessing as mp
import pickle
import time

from .networks import SimpleControlNetwork, create_evolution_network
from ..dynamics import TVCPlant, TVCParameters
from ..control import CLFCBFQPFilter, LQRController


@dataclass
class EvolutionParameters:
    """Parameters for evolutionary algorithm"""
    # Population parameters
    population_size: int = 1000  # As mentioned in video
    elite_ratio: float = 0.2     # Top 20% survive
    mutation_ratio: float = 0.6   # 60% are mutations of elite
    random_ratio: float = 0.2     # 20% are completely random (diversity)
    
    # Mutation parameters
    mutation_strength: float = 0.1  # Gaussian noise std
    mutation_decay: float = 0.995   # Decay mutation over generations
    
    # Training parameters
    max_generations: int = 500
    convergence_threshold: float = 1e-4  # Stop if improvement < threshold
    patience: int = 50  # Generations without improvement before stopping
    
    # Simulation parameters
    sim_duration: float = 5.0     # Simulation time per evaluation (seconds)
    sim_dt: float = 0.01          # Simulation timestep
    num_trials: int = 3           # Multiple trials per network
    
    # Fitness parameters
    angle_weight: float = 1.0     # Weight for angular error in fitness
    jerk_weight: float = 0.1      # Weight for motor jerk (smoothness)
    safety_penalty: float = 10.0  # Penalty for constraint violations
    
    # Parallelization
    use_multiprocessing: bool = True
    num_workers: Optional[int] = None  # None = auto-detect


class Individual:
    """Individual in the evolutionary population"""
    
    def __init__(self, network: SimpleControlNetwork):
        self.network = network
        self.fitness = 0.0
        self.age = 0
        self.parent_ids = []  # For tracking lineage
        
    def evaluate_fitness(self, 
                        eval_func: Callable,
                        plant_params: TVCParameters,
                        evo_params: EvolutionParameters,
                        safety_filter: Optional[CLFCBFQPFilter] = None) -> float:
        """Evaluate fitness of this individual"""
        self.fitness = eval_func(self.network, plant_params, evo_params, safety_filter)
        return self.fitness
    
    def mutate(self, strength: float):
        """Apply mutation to the network"""
        self.network.mutate(strength)
        self.age += 1
    
    def copy(self) -> 'Individual':
        """Create a copy of this individual"""
        new_network = create_evolution_network()
        new_network.copy_weights_from(self.network)
        
        new_individual = Individual(new_network)
        new_individual.age = self.age
        new_individual.parent_ids = self.parent_ids.copy()
        
        return new_individual


def evaluate_network_fitness(network: SimpleControlNetwork,
                            plant_params: TVCParameters,
                            evo_params: EvolutionParameters,
                            safety_filter: Optional[CLFCBFQPFilter] = None) -> float:
    """
    Evaluate fitness of a neural network controller
    
    Fitness combines:
    1. Angular error (primary objective)
    2. Motor jerk (smoothness penalty)
    3. Safety violations (hard penalty)
    
    Args:
        network: Neural network to evaluate
        plant_params: Plant parameters
        evo_params: Evolution parameters
        safety_filter: Optional safety filter
        
    Returns:
        Fitness value (higher is better)
    """
    total_fitness = 0.0
    
    # Run multiple trials with different initial conditions
    for trial in range(evo_params.num_trials):
        # Random initial conditions
        initial_angle = np.random.uniform(-0.3, 0.3)  # ±17 degrees
        initial_rate = np.random.uniform(-0.5, 0.5)   # ±0.5 rad/s
        initial_state = np.array([initial_angle, initial_rate])
        
        # Simulate single trial
        trial_fitness = _simulate_trial(
            network, initial_state, plant_params, evo_params, safety_filter
        )
        total_fitness += trial_fitness
    
    return total_fitness / evo_params.num_trials


def _simulate_trial(network: SimpleControlNetwork,
                   initial_state: np.ndarray,
                   plant_params: TVCParameters,
                   evo_params: EvolutionParameters,
                   safety_filter: Optional[CLFCBFQPFilter] = None) -> float:
    """Simulate a single trial and compute fitness"""
    
    # Initialize plant
    plant = TVCPlant(plant_params)
    plant.reset(initial_state)
    
    # Simulation variables
    num_steps = int(evo_params.sim_duration / evo_params.sim_dt)
    thrust = plant_params.nominal_thrust
    
    # Tracking variables
    angle_errors = []
    control_inputs = []
    safety_violations = 0
    
    # Simulation loop
    for step in range(num_steps):
        # Get current state
        state = plant.get_observation(add_noise=False)
        angle, angular_vel = state
        
        # Prepare network input: [thrust, angle, angular_velocity]
        network_input = torch.tensor([thrust, angle, angular_vel], dtype=torch.float32).unsqueeze(0)
        
        # Get control from network
        with torch.no_grad():
            control_raw = network(network_input).item()
        
        # Apply safety filter if provided
        if safety_filter is not None:
            filter_result = safety_filter.filter_control(control_raw, state)
            control = filter_result['control']
            if not filter_result['feasible']:
                safety_violations += 1
        else:
            control = np.clip(control_raw, -plant_params.max_gimbal_angle, plant_params.max_gimbal_angle)
        
        # Check safety constraints manually if no filter
        if not plant.is_safe():
            safety_violations += 1
        
        # Store for fitness calculation
        angle_errors.append(abs(angle))
        control_inputs.append(control)
        
        # Step plant
        plant.step(control, evo_params.sim_dt, add_disturbance=True)
    
    # Compute fitness components
    
    # 1. Angular error (primary objective - minimize RMS error)
    rms_angle_error = np.sqrt(np.mean(np.array(angle_errors)**2))
    angle_fitness = 1.0 / (1.0 + rms_angle_error)  # Higher is better
    
    # 2. Motor jerk (smoothness - penalize rapid control changes)
    if len(control_inputs) > 1:
        control_diff = np.diff(control_inputs)
        control_jerk = np.sum(np.abs(control_diff)) / evo_params.sim_dt
        jerk_penalty = control_jerk / len(control_inputs)  # Normalize
    else:
        jerk_penalty = 0.0
    
    # 3. Safety penalty
    safety_penalty = safety_violations * evo_params.safety_penalty
    
    # Combined fitness (higher is better)
    fitness = (evo_params.angle_weight * angle_fitness 
               - evo_params.jerk_weight * jerk_penalty 
               - safety_penalty)
    
    return max(fitness, 0.001)  # Ensure positive fitness


class EvolutionaryTrainer:
    """
    Evolutionary trainer for TVC neural networks
    
    Implements the algorithm described in the video:
    1. Initialize population of random networks
    2. Evaluate fitness of each network
    3. Select elite performers
    4. Generate next generation through mutation
    5. Repeat until convergence
    """
    
    def __init__(self, 
                 plant_params: TVCParameters,
                 evo_params: Optional[EvolutionParameters] = None,
                 use_safety_filter: bool = False):
        
        self.plant_params = plant_params
        self.evo_params = evo_params or EvolutionParameters()
        
        # Setup safety filter if requested
        self.safety_filter = None
        if use_safety_filter:
            plant = TVCPlant(plant_params)
            lqr = LQRController(plant)
            self.safety_filter = CLFCBFQPFilter(plant, lqr)
        
        # Initialize population
        self.population: List[Individual] = []
        self.generation = 0
        self.best_fitness_history = []
        self.mean_fitness_history = []
        
        # Setup multiprocessing
        if self.evo_params.num_workers is None:
            self.evo_params.num_workers = max(1, mp.cpu_count() - 1)
        
        self._initialize_population()
        
    def _initialize_population(self):
        """Initialize random population"""
        print(f"Initializing population of {self.evo_params.population_size} networks...")
        
        self.population = []
        for i in range(self.evo_params.population_size):
            network = create_evolution_network()
            individual = Individual(network)
            individual.parent_ids = [i]  # Original random individual
            self.population.append(individual)
            
        print("Population initialized!")
    
    def _evaluate_population(self):
        """Evaluate fitness of entire population"""
        print(f"Evaluating generation {self.generation}...")
        start_time = time.time()
        
        if self.evo_params.use_multiprocessing and (self.evo_params.num_workers or 0) > 1:
            # Parallel evaluation
            with ProcessPoolExecutor(max_workers=self.evo_params.num_workers) as executor:
                futures = []
                for individual in self.population:
                    future = executor.submit(
                        evaluate_network_fitness,
                        individual.network,
                        self.plant_params,
                        self.evo_params,
                        self.safety_filter
                    )
                    futures.append(future)
                
                # Collect results
                for i, future in enumerate(futures):
                    self.population[i].fitness = future.result()
        else:
            # Sequential evaluation
            for individual in self.population:
                individual.evaluate_fitness(
                    evaluate_network_fitness,
                    self.plant_params,
                    self.evo_params,
                    self.safety_filter
                )
        
        eval_time = time.time() - start_time
        print(f"Evaluation completed in {eval_time:.2f}s")
        
    def _select_and_reproduce(self):
        """Select elite and create next generation"""
        # Sort by fitness (descending)
        self.population.sort(key=lambda x: x.fitness, reverse=True)
        
        # Record statistics
        fitnesses = [ind.fitness for ind in self.population]
        self.best_fitness_history.append(max(fitnesses))
        self.mean_fitness_history.append(np.mean(fitnesses))
        
        # Elite selection
        elite_size = int(self.evo_params.elite_ratio * self.evo_params.population_size)
        elite = self.population[:elite_size]
        
        # Create next generation
        new_population = []
        
        # 1. Keep elite
        for individual in elite:
            new_population.append(individual.copy())
        
        # 2. Mutations of elite
        mutation_size = int(self.evo_params.mutation_ratio * self.evo_params.population_size)
        current_mutation_strength = self.evo_params.mutation_strength * (self.evo_params.mutation_decay ** self.generation)
        
        for _ in range(mutation_size):
            # Select parent from elite
            parent = random.choice(elite)
            child = parent.copy()
            child.mutate(current_mutation_strength)
            child.parent_ids = [self.population.index(parent)]
            new_population.append(child)
        
        # 3. Random individuals (for diversity)
        random_size = self.evo_params.population_size - len(new_population)
        for i in range(random_size):
            network = create_evolution_network()
            individual = Individual(network)
            individual.parent_ids = [f"random_gen_{self.generation}_{i}"]
            new_population.append(individual)
        
        self.population = new_population
        
    def train(self) -> Dict:
        """
        Run the evolutionary training process
        
        Returns:
            Training results and best network
        """
        print(f"Starting evolutionary training:")
        print(f"Population size: {self.evo_params.population_size}")
        print(f"Max generations: {self.evo_params.max_generations}")
        print(f"Using safety filter: {self.safety_filter is not None}")
        print("=" * 50)
        
        best_fitness = 0.0
        last_generation = -1
        generations_without_improvement = 0
        
        for generation in range(self.evo_params.max_generations):
            self.generation = generation
            last_generation = generation
            
            # Evaluate population
            self._evaluate_population()
            
            # Check for improvement
            current_best = max(ind.fitness for ind in self.population)
            improvement = current_best - best_fitness
            
            if improvement > self.evo_params.convergence_threshold:
                best_fitness = current_best
                generations_without_improvement = 0
            else:
                generations_without_improvement += 1
            
            # Print progress
            mean_fitness = np.mean([ind.fitness for ind in self.population])
            print(f"Gen {generation:3d}: Best={current_best:.4f}, "
                  f"Mean={mean_fitness:.4f}, "
                  f"Improvement={improvement:.6f}")
            
            # Check convergence
            if generations_without_improvement >= self.evo_params.patience:
                print(f"Converged after {generation+1} generations (no improvement for {self.evo_params.patience})")
                break
                
            # Create next generation
            self._select_and_reproduce()
        
        # Get best individual
        self.population.sort(key=lambda x: x.fitness, reverse=True)
        best_individual = self.population[0]
        
        print(f"\nTraining completed!")
        print(f"Best fitness: {best_individual.fitness:.4f}")
        print(f"Best individual age: {best_individual.age}")
        
        return {
            'best_network': best_individual.network,
            'best_fitness': best_individual.fitness,
            'generations': last_generation + 1,
            'fitness_history': {
                'best': self.best_fitness_history,
                'mean': self.mean_fitness_history
            },
            'best_individual': best_individual
        }
    
    def save_results(self, results: Dict, filepath: str):
        """Save training results"""
        with open(filepath, 'wb') as f:
            pickle.dump(results, f)
        print(f"Results saved to {filepath}")
    
    def plot_fitness_history(self, results: Dict):
        """Plot fitness evolution over generations"""
        plt.figure(figsize=(10, 6))
        generations = range(len(results['fitness_history']['best']))
        
        plt.plot(generations, results['fitness_history']['best'], 'b-', label='Best Fitness')
        plt.plot(generations, results['fitness_history']['mean'], 'r--', label='Mean Fitness')
        
        plt.xlabel('Generation')
        plt.ylabel('Fitness')
        plt.title('Evolutionary Training Progress')
        plt.legend()
        plt.grid(True)
        plt.show()


def test_evolutionary_training():
    """Test the evolutionary training system"""
    print("Testing Evolutionary Training")
    print("=" * 40)
    
    # Use smaller parameters for testing
    plant_params = TVCParameters()
    
    evo_params = EvolutionParameters(
        population_size=20,  # Small for testing
        max_generations=10,
        sim_duration=2.0,    # Shorter simulation
        use_multiprocessing=False  # Easier debugging
    )
    
    # Test without safety filter first
    trainer = EvolutionaryTrainer(plant_params, evo_params, use_safety_filter=False)
    
    print("Running evolution...")
    results = trainer.train()
    
    print(f"Training completed:")
    print(f"Best fitness: {results['best_fitness']:.4f}")
    print(f"Generations: {results['generations']}")
    
    # Test the best network
    best_network = results['best_network']
    plant = TVCPlant(plant_params)
    plant.reset(np.array([0.2, 0.1]))
    
    print("\nTesting best network:")
    for i in range(10):
        state = plant.get_observation(add_noise=False)
        thrust = plant_params.nominal_thrust
        
        network_input = torch.tensor([thrust, state[0], state[1]], dtype=torch.float32).unsqueeze(0)
        
        with torch.no_grad():
            control = best_network(network_input).item()
        
        plant.step(control, add_disturbance=False)
        
        if i % 2 == 0:
            print(f"Step {i}: θ={state[0]:.3f}, θ̇={state[1]:.3f}, u={control:.3f}")


if __name__ == "__main__":
    test_evolutionary_training()