"""
Neural Network Architectures for TVC Control

This module defines the neural network architectures used for:
1. Neuro-evolutionary control (single-axis networks)
2. Residual PPO policies
3. Value function approximation

Author: Generated by GitHub Copilot
"""

import torch
import torch.nn as nn
import numpy as np
from typing import Tuple, List, Optional, cast
from dataclasses import dataclass, field


@dataclass
class NetworkConfig:
    """Configuration for neural network architectures"""
    # Input/output dimensions
    input_dim: int = 3  # [thrust, angle, angular_velocity] as in video
    output_dim: int = 1  # [gimbal_angle]
    
    # Architecture
    hidden_layers: List[int] = field(default_factory=lambda: [16, 16])  # Hidden layer sizes
    activation: str = 'tanh'  # 'tanh', 'relu', 'sigmoid'
    output_activation: str = 'tanh'  # Output activation for bounded control
    
    # Control bounds
    output_scale: float = 1.0  # Scale factor for output (max gimbal angle)
    
    def __post_init__(self):
        # Ensure valid scales/activation names if needed
        pass


class SimpleControlNetwork(nn.Module):
    """
    Simple feedforward network for TVC control
    
    As described in the video:
    - Inputs: thrust, angle, angular_velocity (3 inputs)
    - Hidden: 2 small hidden layers 
    - Output: gimbal_angle (1 output)
    """
    
    def __init__(self, config: NetworkConfig):
        super().__init__()
        self.config = config
        
        # Build layers
        layers = []
        prev_dim = config.input_dim
        
        # Hidden layers
        for hidden_dim in config.hidden_layers:
            layers.extend([
                nn.Linear(prev_dim, hidden_dim),
                self._get_activation(config.activation)
            ])
            prev_dim = hidden_dim
            
        # Output layer
        layers.append(nn.Linear(prev_dim, config.output_dim))
        
        # Output activation for bounded control
        if config.output_activation:
            layers.append(self._get_activation(config.output_activation))
            
        self.network = nn.Sequential(*layers)
        
        # Initialize weights
        self._initialize_weights()
        
    def _get_activation(self, activation: str) -> nn.Module:
        """Get activation function by name"""
        activations = {
            'tanh': nn.Tanh(),
            'relu': nn.ReLU(),
            'sigmoid': nn.Sigmoid(),
            'leaky_relu': nn.LeakyReLU(),
        }
        return activations[activation]
    
    def _initialize_weights(self):
        """Initialize network weights with Xavier initialization"""
        for layer in self.network:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight)
                nn.init.zeros_(layer.bias)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass
        
        Args:
            x: Input tensor [batch_size, 3] containing [thrust, angle, angular_velocity]
            
        Returns:
            Output tensor [batch_size, 1] containing [gimbal_angle]
        """
        output = self.network(x)
        # Scale output to control bounds
        return output * self.config.output_scale
    
    def get_weights_as_vector(self) -> np.ndarray:
        """Get all network weights as a flat vector (for evolution)"""
        weights = []
        for param in self.parameters():
            weights.append(param.data.cpu().numpy().flatten())
        return np.concatenate(weights)
    
    def set_weights_from_vector(self, weights: np.ndarray):
        """Set network weights from a flat vector (for evolution)"""
        idx = 0
        for param in self.parameters():
            param_size = param.numel()
            param.data = torch.from_numpy(
                weights[idx:idx+param_size].reshape(param.shape)
            ).float()
            idx += param_size
    
    def copy_weights_from(self, other: 'SimpleControlNetwork'):
        """Copy weights from another network"""
        self.load_state_dict(other.state_dict())
    
    def mutate(self, mutation_strength: float = 0.1):
        """Add Gaussian noise to weights (for evolution)"""
        with torch.no_grad():
            for param in self.parameters():
                noise = torch.randn_like(param) * mutation_strength
                param.add_(noise)
    
    def count_parameters(self) -> int:
        """Count total number of parameters"""
        return sum(p.numel() for p in self.parameters())
    
    def __getstate__(self):
        """Custom serialization for multiprocessing compatibility"""
        # Save only the essential state: config and trained weights
        return {
            'config': self.config,
            'state_dict': self.state_dict()
        }
    
    def __setstate__(self, state):
        """Custom deserialization for multiprocessing compatibility"""
        # Initialize the module first
        super().__init__()
        
        # Restore the config
        self.config = state['config']
        
        # Rebuild the network architecture
        layers = []
        prev_dim = self.config.input_dim
        
        # Hidden layers
        for hidden_dim in self.config.hidden_layers:
            layers.extend([
                nn.Linear(prev_dim, hidden_dim),
                self._get_activation(self.config.activation)
            ])
            prev_dim = hidden_dim
            
        # Output layer
        layers.append(nn.Linear(prev_dim, self.config.output_dim))
        
        # Output activation for bounded control
        if self.config.output_activation:
            layers.append(self._get_activation(self.config.output_activation))
            
        self.network = nn.Sequential(*layers)
        
        # Load the trained weights
        self.load_state_dict(state['state_dict'])


class ResidualPolicyNetwork(nn.Module):
    """
    Residual policy network for PPO
    
    Outputs residual corrections to LQR baseline:
    u_total = u_LQR + π_residual(state)
    """
    
    def __init__(self, config: NetworkConfig):
        super().__init__()
        self.config = config
        
        # State encoder (larger than evolution network)
        self.encoder = nn.Sequential(
            nn.Linear(config.input_dim, 64),
            nn.Tanh(),
            nn.Linear(64, 64),
            nn.Tanh(),
            nn.Linear(64, 32),
            nn.Tanh()
        )
        
        # Policy head (mean of action distribution)
        self.policy_mean = nn.Sequential(
            nn.Linear(32, 16),
            nn.Tanh(),
            nn.Linear(16, config.output_dim),
            nn.Tanh()  # Bounded output
        )
        
        # Policy log std (learnable parameter)
        self.log_std = nn.Parameter(torch.zeros(config.output_dim))
        
        self._initialize_weights()
        
    def _initialize_weights(self):
        """Initialize weights for stable training"""
        def _init_linear(m: nn.Module) -> None:
            if isinstance(m, nn.Linear):
                nn.init.orthogonal_(m.weight)
                nn.init.zeros_(m.bias)

        self.encoder.apply(_init_linear)
        self.policy_mean.apply(_init_linear)
                    
        # Small initial log_std for exploration
        nn.init.constant_(self.log_std, -1.0)
    
    def forward(self, state: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Forward pass for residual policy
        
        Args:
            state: State tensor [batch_size, input_dim]
            
        Returns:
            (mean, std) of action distribution
        """
        features = self.encoder(state)
        mean = self.policy_mean(features) * self.config.output_scale
        std = torch.exp(self.log_std).expand_as(mean)
        
        return mean, std


class ValueNetwork(nn.Module):
    """Value function network for PPO critic"""
    
    def __init__(self, config: NetworkConfig):
        super().__init__()
        self.config = config
        
        self.network = nn.Sequential(
            nn.Linear(config.input_dim, 64),
            nn.Tanh(),
            nn.Linear(64, 64),
            nn.Tanh(),
            nn.Linear(64, 32),
            nn.Tanh(),
            nn.Linear(32, 1)  # Single value output
        )
        
        self._initialize_weights()
        
    def _initialize_weights(self):
        """Initialize weights for stable value learning"""
        def _init_linear(m: nn.Module) -> None:
            if isinstance(m, nn.Linear):
                nn.init.orthogonal_(m.weight)
                nn.init.zeros_(m.bias)
        
        self.network.apply(_init_linear)
        
        # Small final layer for stable value estimates
        final_layer = cast(nn.Linear, self.network[-1])
        nn.init.orthogonal_(final_layer.weight, gain=0.1)
    
    def forward(self, state: torch.Tensor) -> torch.Tensor:
        """
        Compute state value
        
        Args:
            state: State tensor [batch_size, input_dim]
            
        Returns:
            Value tensor [batch_size, 1]
        """
        return self.network(state)


def create_evolution_network(max_gimbal_angle: float = np.pi/6) -> SimpleControlNetwork:
    """Create a network for evolutionary training as described in video"""
    config = NetworkConfig(
        input_dim=3,  # [thrust, angle, angular_velocity]
        output_dim=1,  # [gimbal_angle]
        hidden_layers=[16, 16],  # Small networks for fast evolution
        activation='tanh',
        output_activation='tanh',
        output_scale=max_gimbal_angle  # Scale to max gimbal angle
    )
    return SimpleControlNetwork(config)


def create_residual_policy(max_gimbal_angle: float = np.pi/6) -> ResidualPolicyNetwork:
    """Create a residual policy network for PPO"""
    config = NetworkConfig(
        input_dim=2,  # [angle, angular_velocity] for residual policy
        output_dim=1,  # [residual_gimbal_angle]
        output_scale=max_gimbal_angle * 0.5  # Residual is smaller than baseline
    )
    return ResidualPolicyNetwork(config)


def create_value_network() -> ValueNetwork:
    """Create a value network for PPO critic"""
    config = NetworkConfig(
        input_dim=2,  # [angle, angular_velocity]
        output_dim=1   # [value]
    )
    return ValueNetwork(config)


def test_networks():
    """Test network implementations"""
    print("Testing Neural Network Architectures")
    print("=" * 40)
    
    # Test evolution network
    print("1. Evolution Network:")
    evo_net = create_evolution_network()
    print(f"   Parameters: {evo_net.count_parameters()}")
    
    # Test input (batch_size=5)
    thrust = torch.tensor([15.0, 15.0, 15.0, 15.0, 15.0])
    angle = torch.tensor([0.1, 0.2, -0.1, 0.0, 0.3])
    angular_vel = torch.tensor([0.05, -0.1, 0.02, 0.0, -0.05])
    
    evo_input = torch.stack([thrust, angle, angular_vel], dim=1)
    evo_output = evo_net(evo_input)
    
    print(f"   Input shape: {evo_input.shape}")
    print(f"   Output shape: {evo_output.shape}")
    print(f"   Output range: [{evo_output.min().item():.3f}, {evo_output.max().item():.3f}]")
    
    # Test weight manipulation
    weights = evo_net.get_weights_as_vector()
    print(f"   Weight vector size: {len(weights)}")
    
    # Test mutation
    evo_net.mutate(0.1)
    print("   Mutation applied")
    
    # Test residual policy
    print("\n2. Residual Policy Network:")
    residual_net = create_residual_policy()
    
    # Test with state input (no thrust for residual)
    state_input = torch.stack([angle, angular_vel], dim=1)
    mean, std = residual_net(state_input)
    
    print(f"   Input shape: {state_input.shape}")
    print(f"   Mean shape: {mean.shape}")
    print(f"   Std shape: {std.shape}")
    print(f"   Mean range: [{mean.min().item():.3f}, {mean.max().item():.3f}]")
    print(f"   Std range: [{std.min().item():.3f}, {std.max().item():.3f}]")
    
    # Test value network
    print("\n3. Value Network:")
    value_net = create_value_network()
    values = value_net(state_input)
    
    print(f"   Input shape: {state_input.shape}")
    print(f"   Value shape: {values.shape}")
    print(f"   Value range: [{values.min().item():.3f}, {values.max().item():.3f}]")
    
    print("\nAll networks tested successfully!")