"""
Residual PPO Training for TVC Control

This module implements residual reinforcement learning with PPO using TorchRL.
The approach learns a residual policy that corrects the MPC baseline:

u_total = u_MPC + π_residual(state)

The residual policy is trained with PPO while the safety filter ensures all
actions remain within safe constraints during training and deployment.

Author: Generated by GitHub Copilot
"""

import torch
import torch.nn as nn
import numpy as np
from typing import Dict, Optional, Tuple, List
from dataclasses import dataclass
import time

# TorchRL imports
from torchrl.collectors import SyncDataCollector
from torchrl.data.replay_buffers import TensorDictReplayBuffer, LazyTensorStorage, SamplerWithoutReplacement
from torchrl.envs import EnvBase, TransformedEnv
from torchrl.modules import ProbabilisticActor, ValueOperator, TanhNormal
from torchrl.data.tensor_specs import (
    CompositeSpec,
    UnboundedContinuousTensorSpec,
    BoundedTensorSpec,
    DiscreteTensorSpec,
)
from torchrl.objectives import ClipPPOLoss
from torchrl.objectives.value import GAE
from tensordict import TensorDict
from tensordict.nn import TensorDictModule
from tensordict.nn.distributions import NormalParamExtractor

from .networks import ResidualPolicyNetwork, ValueNetwork, create_residual_policy, create_value_network
from ..dynamics import TVCPlant, TVCParameters
from ..control import MPCController, CLFCBFQPFilter
from ..utils.training_scenarios import ScenarioGenerator, TrainingScenario
from ..utils.curriculum_learning import CurriculumManager, create_adaptive_curriculum


@dataclass
class PPOParameters:
    """PPO training hyperparameters"""
    # Training parameters
    total_frames: int = 1_000_000
    frames_per_batch: int = 2048
    mini_batch_size: int = 64
    epochs_per_batch: int = 10
    
    # PPO parameters
    clip_epsilon: float = 0.2
    entropy_bonus: float = 0.01
    value_loss_coeff: float = 0.5
    max_grad_norm: float = 0.5
    
    # Learning rates
    lr_actor: float = 3e-4
    lr_critic: float = 3e-4
    lr_scheduler_gamma: float = 0.99
    
    # GAE parameters
    gamma: float = 0.99
    lambda_gae: float = 0.95
    
    # Environment parameters
    max_episode_length: int = 1000  # 5 seconds at 200Hz
    num_envs: int = 1  # Single environment for simplicity
    
    # Residual policy constraints
    residual_scale: float = 0.3  # Maximum residual as fraction of max control
    
    # Scenario-based training
    use_scenarios: bool = True
    scenario_curriculum: bool = True
    curriculum_episodes: Optional[List[int]] = None


class TVCResidualEnv(EnvBase):
    """
    TorchRL environment wrapper for TVC residual learning
    
    State: [angle, angular_velocity]
    Action: [residual_control] (added to LQR baseline)
    Reward: Based on tracking performance and control effort
    """
    
    def __init__(self, 
                 plant_params: TVCParameters,
                 ppo_params: PPOParameters,
                 use_safety_filter: bool = True,
                 device: str = "cpu",
                 scenario_gen: Optional[ScenarioGenerator] = None,
                 curriculum: Optional[CurriculumManager] = None):
        
        super().__init__(device=device)
        
        self.plant_params = plant_params
        self.ppo_params = ppo_params
        self.use_safety_filter = use_safety_filter
        
        # Initialize components
        self.plant = TVCPlant(plant_params)
        self.lqr = MPCController(self.plant)
        
        if use_safety_filter:
            self.safety_filter = CLFCBFQPFilter(self.plant, self.lqr)
        else:
            self.safety_filter = None

        # Scenarios / curriculum
        self.scenario_gen = scenario_gen
        self.curriculum = curriculum
        self.current_scenario: Optional[TrainingScenario] = None

        # Environment state
        self.step_count = 0
        self.episode_reward = 0.0
        self.env_dt = 0.005
        self.episode_max_steps = int(self.ppo_params.max_episode_length)
        
        # Define observation and action specs
        self._make_specs()
    
    def _make_specs(self):
        """Define observation and action specifications"""
        # Observation spec: [angle, angular_velocity]
        self.observation_spec = CompositeSpec(
            observation=UnboundedContinuousTensorSpec(shape=torch.Size([2]), device=self.device)
        ).to(self.device)

        # Action spec: [residual_control]
        max_residual = float(self.plant_params.max_gimbal_angle * self.ppo_params.residual_scale)
        self.action_spec = BoundedTensorSpec(
            low=torch.tensor([-max_residual], dtype=torch.float32, device=self.device),
            high=torch.tensor([max_residual], dtype=torch.float32, device=self.device),
            device=self.device,
        )
        
        # Reward and done specs
        self.reward_spec = UnboundedContinuousTensorSpec(shape=torch.Size([1]), device=self.device)
        # Full done spec: done, terminated, truncated
        self.full_done_spec = CompositeSpec(
            done=DiscreteTensorSpec(n=2, shape=torch.Size([1]), dtype=torch.bool, device=self.device),
            terminated=DiscreteTensorSpec(n=2, shape=torch.Size([1]), dtype=torch.bool, device=self.device),
            truncated=DiscreteTensorSpec(n=2, shape=torch.Size([1]), dtype=torch.bool, device=self.device),
        ).to(self.device)
    
    def _reset(self, tensordict: TensorDict, **kwargs) -> TensorDict:
        """Reset environment to initial state"""
        # Pick scenario if enabled
        self.current_scenario = None
        if self.ppo_params.use_scenarios and self.scenario_gen is not None:
            if self.ppo_params.scenario_curriculum and self.curriculum is not None:
                self.current_scenario = self.curriculum.get_next_scenario()
            else:
                all_scen = self.scenario_gen.scenarios
                idx = np.random.choice(len(all_scen))
                self.current_scenario = all_scen[idx]
        
        # Initial conditions
        if self.current_scenario is not None:
            initial_angle = np.random.uniform(*self.current_scenario.initial_angle_range)
            initial_rate = np.random.uniform(*self.current_scenario.initial_rate_range)
            # Cap episode length by scenario duration
            self.episode_max_steps = min(
                int(self.ppo_params.max_episode_length),
                max(1, int(getattr(self.current_scenario, 'episode_duration', self.episode_max_steps * self.env_dt) / self.env_dt))
            )
        else:
            # Random initial conditions (default)
            initial_angle = np.random.uniform(-0.2, 0.2)  # ±11 degrees
            initial_rate = np.random.uniform(-0.3, 0.3)   # ±0.3 rad/s
            self.episode_max_steps = int(self.ppo_params.max_episode_length)
        
        self.plant.reset(np.array([initial_angle, initial_rate]))
        self.step_count = 0
        self.episode_reward = 0.0
        
        # Get initial observation
        state = self.plant.get_observation(add_noise=True)
        observation = torch.tensor(state, dtype=torch.float32, device=self.device)
        
        # Create output tensordict
        out = TensorDict(
            {
                "observation": observation,
                "done": torch.tensor([False], dtype=torch.bool, device=self.device),
                "terminated": torch.tensor([False], dtype=torch.bool, device=self.device),
                "truncated": torch.tensor([False], dtype=torch.bool, device=self.device),
            },
            batch_size=(),
            device=self.device,
        )
        
        return out
    
    def _step(self, tensordict: TensorDict) -> TensorDict:
        """Execute one environment step"""
        # Extract action (residual control)
        residual_action = float(tensordict["action"].squeeze().cpu().item())
        
        # Get current state
        current_state = self.plant.get_observation(add_noise=False)
        
        # Compute LQR baseline control
        u_lqr = self.lqr.control(current_state)
        
        # Combine with residual
        u_total = u_lqr + residual_action
        
        # Apply safety filter if enabled
        if self.safety_filter is not None:
            filter_result = self.safety_filter.filter_control(u_total, current_state)
            u_safe = filter_result['control']
            safety_intervention = filter_result['intervention']
        else:
            u_safe = np.clip(u_total, -self.plant_params.max_gimbal_angle, self.plant_params.max_gimbal_angle)
            safety_intervention = False
        
        # Step plant
        next_state = self.plant.step(u_safe, dt=self.env_dt, add_disturbance=True)
        
        # Compute reward
        reward = self._compute_reward(current_state, residual_action, u_safe, safety_intervention)
        
        # Check termination conditions
        self.step_count += 1
        terminated = (self.step_count >= self.episode_max_steps or 
                 not self.plant.is_safe())
        
        # Create observation tensors (current and next)
        observation = torch.tensor(next_state, dtype=torch.float32, device=self.device)
        prev_observation = torch.tensor(current_state, dtype=torch.float32, device=self.device)
        
        # Update episode reward
        self.episode_reward += reward
        
        # Create output tensordict
        out = TensorDict(
            {
                "observation": prev_observation,
                "reward": torch.tensor([reward], dtype=torch.float32, device=self.device),
                "done": torch.tensor([False], dtype=torch.bool, device=self.device),
                "terminated": torch.tensor([False], dtype=torch.bool, device=self.device),
                "truncated": torch.tensor([False], dtype=torch.bool, device=self.device),
                "next": TensorDict(
                    {
                        "observation": observation,
                        "reward": torch.tensor([reward], dtype=torch.float32, device=self.device),
                        "done": torch.tensor([terminated], dtype=torch.bool, device=self.device),
                        "terminated": torch.tensor([terminated], dtype=torch.bool, device=self.device),
                        "truncated": torch.tensor([False], dtype=torch.bool, device=self.device),
                    },
                    batch_size=(),
                    device=self.device,
                ),
            },
            batch_size=(),
            device=self.device,
        )
        
        return out
    
    def _compute_reward(self, state: np.ndarray, residual_action: float, 
                       final_control: float, safety_intervention: bool) -> float:
        """
        Compute reward for current step
        
        Reward components:
        1. Tracking performance (negative angle and rate errors)
        2. Control effort penalty
        3. Safety penalty
        4. Residual penalty (encourage small residuals)
        """
        angle, angular_rate = state
        
        # 1. Tracking performance (primary objective)
        angle_error = abs(angle)
        rate_error = abs(angular_rate)
        tracking_reward = -(angle_error + 0.1 * rate_error)
        
        # 2. Control effort penalty
        control_penalty = -0.01 * abs(final_control)
        
        # 3. Safety penalty
        safety_penalty = -1.0 if safety_intervention else 0.0
        
        # 4. Residual penalty (encourage using LQR when possible)
        residual_penalty = -0.005 * abs(residual_action)
        
        # 5. Stability bonus (reward being close to upright)
        stability_bonus = 1.0 * np.exp(-10 * angle_error)
        
        total_reward = (tracking_reward + control_penalty + safety_penalty + 
                       residual_penalty + stability_bonus)
        
        return float(total_reward)
    
    def _set_seed(self, seed: Optional[int]):
        """Set random seed"""
        if seed is not None:
            np.random.seed(seed)
            torch.manual_seed(seed)


class ResidualPPOTrainer:
    """
    Residual PPO trainer for TVC control
    
    Trains a residual policy that corrects LQR baseline while maintaining safety
    through the CBF-QP filter during both training and deployment.
    """
    
    def __init__(self,
                 plant_params: TVCParameters,
                 ppo_params: Optional[PPOParameters] = None,
                 use_safety_filter: bool = True,
                 device: str = "cpu"):
        
        self.plant_params = plant_params
        self.ppo_params = ppo_params or PPOParameters()
        self.use_safety_filter = use_safety_filter
        self.device = device
        
        # Scenarios / Curriculum
        self.scenario_gen: Optional[ScenarioGenerator] = None
        self.curriculum: Optional[CurriculumManager] = None
        if self.ppo_params.use_scenarios:
            self.scenario_gen = ScenarioGenerator()
            if self.ppo_params.scenario_curriculum:
                self.curriculum = create_adaptive_curriculum(self.scenario_gen)

        # Create environment
        self.env = TVCResidualEnv(
            plant_params,
            self.ppo_params,
            use_safety_filter,
            device,
            scenario_gen=self.scenario_gen,
            curriculum=self.curriculum,
        )
        
    # Optionally check environment specs (disabled to avoid rollout issues during init)
    # check_env_specs(self.env)
        
        # Create actor-critic networks
        self._create_networks()
        
        # Create data collector and replay buffer
        self._create_collector()
        
        # Create loss function and optimizers
        self._create_loss_and_optimizers()
        
        # Training statistics
        self.training_stats = {
            'episode_rewards': [],
            'episode_lengths': [],
            'policy_losses': [],
            'value_losses': [],
            'safety_interventions': []
        }
    
    def _create_networks(self):
        """Create actor and critic networks"""
        # Actor network (residual policy)
        actor_net = create_residual_policy(self.plant_params.max_gimbal_angle)
        
        # Convert to TensorDictModule for TorchRL
        self.actor_module = TensorDictModule(
            actor_net,
            in_keys=["observation"],
            out_keys=["loc", "scale"]
        )
        
        # Wrap in probabilistic actor (bounded via spec)
        self.actor = ProbabilisticActor(
            module=self.actor_module,
            in_keys=["loc", "scale"],
            out_keys=["action"],
            distribution_class=TanhNormal,
            return_log_prob=True,
            spec=self.env.action_spec,
        )
        
        # Critic network (value function)
        critic_net = create_value_network()
        self.critic = ValueOperator(
            module=critic_net,
            in_keys=["observation"]
        )
    
    def _create_collector(self):
        """Create data collector and replay buffer"""
        # Data collector
        self.collector = SyncDataCollector(
            self.env,
            self.actor,
            frames_per_batch=self.ppo_params.frames_per_batch,
            total_frames=self.ppo_params.total_frames
        )
        
        # Replay buffer for mini-batch training
        self.replay_buffer = TensorDictReplayBuffer(
            storage=LazyTensorStorage(self.ppo_params.frames_per_batch),
            sampler=SamplerWithoutReplacement(),
            batch_size=self.ppo_params.mini_batch_size
        )
    
    def _create_loss_and_optimizers(self):
        """Create loss function and optimizers"""
        # PPO loss
        self.loss_fn = ClipPPOLoss(
            actor=self.actor,
            critic=self.critic,
            clip_epsilon=self.ppo_params.clip_epsilon,
            entropy_coef=self.ppo_params.entropy_bonus,
            normalize_advantage=True
        )
        
        # GAE for advantage estimation
        self.adv_fn = GAE(
            value_network=self.critic,
            gamma=self.ppo_params.gamma,
            lmbda=self.ppo_params.lambda_gae,
            average_gae=True
        )
        
        # Optimizers
        self.actor_optimizer = torch.optim.Adam(
            self.actor.parameters(),
            lr=self.ppo_params.lr_actor
        )
        
        self.critic_optimizer = torch.optim.Adam(
            self.critic.parameters(),
            lr=self.ppo_params.lr_critic
        )
        
        # Learning rate schedulers
        self.actor_scheduler = torch.optim.lr_scheduler.ExponentialLR(
            self.actor_optimizer,
            gamma=self.ppo_params.lr_scheduler_gamma
        )
        
        self.critic_scheduler = torch.optim.lr_scheduler.ExponentialLR(
            self.critic_optimizer,
            gamma=self.ppo_params.lr_scheduler_gamma
        )
    
    def train(self) -> Dict:
        """
        Train the residual PPO policy
        
        Returns:
            Training results and statistics
        """
        print(f"Starting Residual PPO Training:")
        print(f"Total frames: {self.ppo_params.total_frames:,}")
        print(f"Frames per batch: {self.ppo_params.frames_per_batch}")
        print(f"Mini-batch size: {self.ppo_params.mini_batch_size}")
        print(f"Using safety filter: {self.use_safety_filter}")
        print("=" * 50)
        
        start_time = time.time()
        frames_collected = 0
        
        for i, data in enumerate(self.collector):
            # Compute advantages
            with torch.no_grad():
                self.adv_fn(data)
            
            # Add to replay buffer
            self.replay_buffer.extend(data)
            
            # Mini-batch training
            for epoch in range(self.ppo_params.epochs_per_batch):
                for batch in self.replay_buffer:
                    # Compute losses
                    loss_dict = self.loss_fn(batch)
                    
                    # Extract individual losses
                    policy_loss = loss_dict["loss_objective"]
                    value_loss = loss_dict["loss_critic"]
                    entropy_loss = loss_dict.get("loss_entropy", torch.tensor(0.0))
                    
                    # Total loss
                    total_loss = policy_loss + self.ppo_params.value_loss_coeff * value_loss
                    
                    # Actor update
                    self.actor_optimizer.zero_grad()
                    policy_loss.backward(retain_graph=True)
                    torch.nn.utils.clip_grad_norm_(
                        self.actor.parameters(),
                        self.ppo_params.max_grad_norm
                    )
                    self.actor_optimizer.step()
                    
                    # Critic update
                    self.critic_optimizer.zero_grad()
                    value_loss.backward()
                    torch.nn.utils.clip_grad_norm_(
                        self.critic.parameters(),
                        self.ppo_params.max_grad_norm
                    )
                    self.critic_optimizer.step()
                    
                    # Store statistics
                    self.training_stats['policy_losses'].append(policy_loss.item())
                    self.training_stats['value_losses'].append(value_loss.item())
            
            # Update learning rates
            self.actor_scheduler.step()
            self.critic_scheduler.step()
            
            # Compute episode statistics
            episode_rewards = data["next", "reward"].sum(dim=1)
            episode_lengths = (~data["next", "done"]).sum(dim=1) + 1
            
            self.training_stats['episode_rewards'].extend(episode_rewards.tolist())
            self.training_stats['episode_lengths'].extend(episode_lengths.tolist())
            
            # Progress reporting
            frames_collected += data.numel()
            if i % 10 == 0:
                mean_reward = torch.mean(episode_rewards).item()
                mean_length = torch.mean(episode_lengths.float()).item()
                
                print(f"Batch {i:3d}: "
                      f"Frames {frames_collected:8,}/{self.ppo_params.total_frames:,} "
                      f"Reward {mean_reward:6.2f} "
                      f"Length {mean_length:5.1f}")

            # Periodically update curriculum with short evaluations
            if self.curriculum is not None and i % 5 == 0:
                self._update_curriculum()
        
        training_time = time.time() - start_time
        
        print(f"\nTraining completed in {training_time:.2f}s")
        print(f"Final mean reward: {np.mean(self.training_stats['episode_rewards'][-100:]):.3f}")
        
        return {
            'actor': self.actor,
            'critic': self.critic,
            'training_stats': self.training_stats,
            'training_time': training_time,
            'total_frames': frames_collected
        }

    def _update_curriculum(self, episodes: int = 3):
        """Evaluate current policy on curriculum scenarios and record results"""
        if self.curriculum is None:
            return
        for _ in range(episodes):
            scenario = self.curriculum.get_next_scenario()
            # Run one short evaluation episode
            td = self.env.reset()
            done = False
            steps = 0
            max_steps = getattr(self.env, 'episode_max_steps', self.ppo_params.max_episode_length)
            last_obs = td['observation']
            while not done and steps < max_steps:
                with torch.no_grad():
                    act_td = self.actor(TensorDict({'observation': last_obs}, batch_size=()))
                step_td = self.env.step(act_td)
                done = step_td['next', 'done'].item()
                last_obs = step_td['next', 'observation']
                steps += 1
            # Get final state from env's plant
            final_state = self.env.plant.get_observation(add_noise=False)
            success = (abs(final_state[0]) <= scenario.max_stable_angle and abs(final_state[1]) <= scenario.max_stable_rate)
            self.curriculum.record_episode_result(scenario.name, bool(success), {
                'final_angle': float(final_state[0]),
                'final_rate': float(final_state[1])
            })
    
    def evaluate_policy(self, num_episodes: int = 10) -> Dict:
        """Evaluate trained policy"""
        print(f"Evaluating policy over {num_episodes} episodes...")
        
        episode_rewards = []
        episode_lengths = []
        safety_violations = []
        
        for episode in range(num_episodes):
            td = self.env.reset()
            episode_reward = 0.0
            episode_length = 0
            violations = 0
            
            done = False
            while not done:
                # Prepare input for actor
                obs_td = TensorDict({"observation": td["observation"]}, batch_size=())
                # Get action from policy
                with torch.no_grad():
                    act_td = self.actor(obs_td)
                # Step environment
                step_td = self.env.step(act_td)

                episode_reward += step_td["next", "reward"].item()
                episode_length += 1
                done = step_td["next", "done"].item()
                # Set td for next iteration
                td = TensorDict({"observation": step_td["next", "observation"]}, batch_size=())
                
                if not self.env.plant.is_safe():
                    violations += 1
            
            episode_rewards.append(episode_reward)
            episode_lengths.append(episode_length)
            safety_violations.append(violations)
        
        return {
            'mean_reward': np.mean(episode_rewards),
            'std_reward': np.std(episode_rewards),
            'mean_length': np.mean(episode_lengths),
            'mean_violations': np.mean(safety_violations),
            'episode_rewards': episode_rewards
        }


def test_residual_ppo():
    """Test residual PPO implementation"""
    print("Testing Residual PPO Training")
    print("=" * 40)
    
    # Use small parameters for testing
    plant_params = TVCParameters()
    
    ppo_params = PPOParameters(
        total_frames=5000,      # Small for testing
        frames_per_batch=1000,
        mini_batch_size=64,
        epochs_per_batch=5,
        max_episode_length=100  # Shorter episodes
    )
    
    # Create trainer
    trainer = ResidualPPOTrainer(plant_params, ppo_params, use_safety_filter=True)
    
    print("Running training...")
    results = trainer.train()
    
    print(f"Training completed:")
    print(f"Total frames: {results['total_frames']:,}")
    print(f"Training time: {results['training_time']:.2f}s")
    
    # Evaluate policy
    eval_results = trainer.evaluate_policy(num_episodes=5)
    print(f"\nEvaluation results:")
    print(f"Mean reward: {eval_results['mean_reward']:.3f} ± {eval_results['std_reward']:.3f}")
    print(f"Mean episode length: {eval_results['mean_length']:.1f}")
    print(f"Mean safety violations: {eval_results['mean_violations']:.1f}")