"""
Configuration management for TVC system

This module provides configuration classes and utilities for managing
all the parameters across different components of the TVC system.

Author: Generated by GitHub Copilot
"""

import yaml
import numpy as np
import os
from dataclasses import dataclass, asdict
from typing import Optional, Dict, Any
from pathlib import Path

from src.dynamics.plant import TVCParameters
from src.control.mpc import MPCParameters
from src.control.safety import SafetyParameters
from src.learning.evolution import EvolutionParameters
from src.learning.ppo import PPOParameters


class ConfigObject:
    """Simple configuration object with dot notation access"""
    def __init__(self, config_dict: Dict[str, Any]):
        for key, value in config_dict.items():
            if isinstance(value, dict):
                setattr(self, key, ConfigObject(value))
            else:
                setattr(self, key, value)


def create_config_object(config_dict: Dict[str, Any]) -> ConfigObject:
    """Create a configuration object from dictionary"""
    return ConfigObject(config_dict)


@dataclass
class ExperimentConfig:
    """Complete configuration for TVC experiments"""
    
    # Component configurations
    plant: TVCParameters
    mpc: Optional[MPCParameters] = None
    safety: Optional[SafetyParameters] = None
    evolution: Optional[EvolutionParameters] = None
    ppo: Optional[PPOParameters] = None
    simulation: Optional[Any] = None  # MuJoCoSimParams - avoiding circular import
    
    # Experiment settings
    experiment_name: str = "tvc_experiment"
    output_dir: str = "./results"
    use_safety_filter: bool = True
    save_models: bool = True
    save_plots: bool = True
    
    # Evaluation settings
    eval_episodes: int = 100
    eval_seed: int = 42


def create_default_config() -> ExperimentConfig:
    """Create default configuration for TVC experiments"""
    
    # Plant parameters
    plant = TVCParameters(
        mass=1.0,
        moment_of_inertia=0.1,
        length=1.0,
        nominal_thrust=15.0,
        max_gimbal_angle=0.524,  # 30 degrees
        max_angle=0.785,         # 45 degrees
        max_angular_rate=6.28    # 2π rad/s
    )
    
    # MPC parameters (drop-in replacement for LQR)
    mpc = MPCParameters(
        Q=np.diag([100.0, 10.0]),
        R=1.0,
        N=20,
        dt=0.01,
        du_rate_limit=True,
        warm_start=True,
        terminal_lqr=True,
    )
    
    # Safety parameters
    safety = SafetyParameters(
        angle_cbf_alpha=3.0,
        rate_cbf_alpha=2.0,
        clf_penalty=1000.0
    )
    
    # Evolution parameters
    evolution = EvolutionParameters(
        population_size=1000,
        max_generations=500,
        sim_duration=5.0,
        mutation_strength=0.1
    )
    
    # PPO parameters
    ppo = PPOParameters(
        total_frames=1_000_000,
        frames_per_batch=2048,
        clip_epsilon=0.2,
        lr_actor=3e-4,
        lr_critic=3e-4
    )
    
    # Simulation parameters
    simulation = None
    
    return ExperimentConfig(
        plant=plant,
        mpc=mpc,
        safety=safety,
        evolution=evolution,
        ppo=ppo,
        simulation=simulation
    )


def save_config(config: ExperimentConfig, filepath: str):
    """Save configuration to YAML file"""
    
    # Convert to dictionary
    config_dict = asdict(config)
    
    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    # Save to YAML
    with open(filepath, 'w') as f:
        yaml.dump(config_dict, f, default_flow_style=False, indent=2)
    
    print(f"Configuration saved to {filepath}")


def load_config(filepath: str) -> ExperimentConfig:
    """Load configuration from YAML file"""
    
    with open(filepath, 'r') as f:
        config_dict = yaml.safe_load(f)
    
    # Reconstruct dataclass objects
    plant = TVCParameters(**config_dict['plant'])
    # Support both 'mpc' and legacy 'lqr' keys
    mpc_cfg = config_dict.get('mpc', None)
    if mpc_cfg is None and 'lqr' in config_dict:
        # Map LQR config to MPCParameters fields where possible
        legacy = config_dict['lqr'] or {}
        mapped = {
            'Q': legacy.get('Q', [[100.0, 0.0], [0.0, 10.0]]),
            'R': legacy.get('R', 1.0),
        }
        mpc = MPCParameters(Q=np.array(mapped['Q']), R=float(mapped['R']))
    elif mpc_cfg is not None:
        mpc = MPCParameters(**mpc_cfg)
    else:
        mpc = MPCParameters()
    safety = SafetyParameters(**config_dict['safety'])
    evolution = EvolutionParameters(**config_dict['evolution'])
    ppo = PPOParameters(**config_dict['ppo'])
    simulation = config_dict.get('simulation', None)
    
    # Remove component configs from dict
    for key in ['plant', 'lqr', 'mpc', 'safety', 'evolution', 'ppo', 'simulation']:
        config_dict.pop(key)
    
    return ExperimentConfig(
        plant=plant,
        mpc=mpc,
        safety=safety,
        evolution=evolution,
        ppo=ppo,
        simulation=simulation,
        **config_dict
    )


def create_experiment_configs() -> Dict[str, ExperimentConfig]:
    """Create predefined experiment configurations"""
    
    configs = {}
    
    # 1. Baseline experiment (MPC only)
    baseline = create_default_config()
    baseline.experiment_name = "baseline_mpc"
    baseline.use_safety_filter = False
    configs["baseline"] = baseline
    
    # 2. MPC with safety filter
    lqr_safe = create_default_config()
    lqr_safe.experiment_name = "mpc_with_safety"
    lqr_safe.use_safety_filter = True
    configs["lqr_safe"] = lqr_safe
    
    # 3. Neuro-evolution experiment
    evolution_exp = create_default_config()
    evolution_exp.experiment_name = "neuro_evolution"
    if evolution_exp.evolution is None:
        evolution_exp.evolution = EvolutionParameters()
    evolution_exp.evolution.population_size = 1000
    evolution_exp.evolution.max_generations = 200
    evolution_exp.use_safety_filter = False
    configs["evolution"] = evolution_exp
    
    # 4. Safe neuro-evolution
    safe_evolution = create_default_config()
    safe_evolution.experiment_name = "safe_neuro_evolution"
    if safe_evolution.evolution is None:
        safe_evolution.evolution = EvolutionParameters()
    safe_evolution.evolution.population_size = 800
    safe_evolution.evolution.max_generations = 300
    safe_evolution.use_safety_filter = True
    configs["safe_evolution"] = safe_evolution
    
    # 5. Residual PPO experiment
    ppo_exp = create_default_config()
    ppo_exp.experiment_name = "residual_ppo"
    if ppo_exp.ppo is None:
        ppo_exp.ppo = PPOParameters()
    ppo_exp.ppo.total_frames = 2_000_000
    ppo_exp.use_safety_filter = False
    configs["residual_ppo"] = ppo_exp
    
    # 6. Safe residual PPO
    safe_ppo = create_default_config()
    safe_ppo.experiment_name = "safe_residual_ppo"
    if safe_ppo.ppo is None:
        safe_ppo.ppo = PPOParameters()
    safe_ppo.ppo.total_frames = 1_500_000
    safe_ppo.use_safety_filter = True
    configs["safe_residual_ppo"] = safe_ppo
    
    # 7. Comparison experiment (smaller scale for testing)
    comparison = create_default_config()
    comparison.experiment_name = "comparison_test"
    if comparison.evolution is None:
        comparison.evolution = EvolutionParameters()
    comparison.evolution.population_size = 100
    comparison.evolution.max_generations = 50
    if comparison.ppo is None:
        comparison.ppo = PPOParameters()
    comparison.ppo.total_frames = 100_000
    comparison.eval_episodes = 20
    configs["comparison"] = comparison
    
    return configs


def test_config_system():
    """Test configuration system"""
    print("Testing Configuration System")
    print("=" * 40)
    
    # Test default config creation
    config = create_default_config()
    print(f"Default config created: {config.experiment_name}")
    print(f"Plant mass: {config.plant.mass}")
    if config.evolution is not None:
        print(f"Population size: {config.evolution.population_size}")
    
    # Test saving and loading
    test_path = "./test_config.yaml"
    save_config(config, test_path)
    
    loaded_config = load_config(test_path)
    print(f"Config loaded: {loaded_config.experiment_name}")
    print(f"Plant mass matches: {config.plant.mass == loaded_config.plant.mass}")
    
    # Clean up
    if os.path.exists(test_path):
        os.unlink(test_path)
    
    # Test predefined configs
    configs = create_experiment_configs()
    print(f"Predefined configs: {list(configs.keys())}")
    
    print("Configuration system test completed!")