"""
Metrics collection and analysis for TVC experiments

This module provides comprehensive metrics for evaluating TVC controller
performance including stability, safety, efficiency, and robustness measures.

Author: Generated by GitHub Copilot
"""

import numpy as np
import torch
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass, field
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import json
from pathlib import Path


@dataclass
class EpisodeMetrics:
    """Metrics for a single episode"""
    
    # Basic trajectory data
    time: np.ndarray
    states: np.ndarray
    actions: np.ndarray
    reference: np.ndarray
    
    # Performance metrics
    rms_error: float = 0.0
    max_error: float = 0.0
    settling_time: float = np.inf
    overshoot: float = 0.0
    
    # Safety metrics
    safety_violations: int = 0
    max_angle_violation: float = 0.0
    max_rate_violation: float = 0.0
    
    # Control effort metrics
    total_control_effort: float = 0.0
    max_control_effort: float = 0.0
    control_smoothness: float = 0.0
    motor_jerk: float = 0.0
    
    # Efficiency metrics
    energy_consumption: float = 0.0
    fuel_efficiency: float = 0.0
    
    # Episode outcome
    success: bool = False
    termination_reason: str = "unknown"
    episode_length: int = 0


@dataclass
class ExperimentMetrics:
    """Aggregate metrics for an experiment"""
    
    # Episode metrics
    episodes: List[EpisodeMetrics] = field(default_factory=list)
    
    # Aggregate statistics
    mean_rms_error: float = 0.0
    std_rms_error: float = 0.0
    success_rate: float = 0.0
    mean_settling_time: float = 0.0
    mean_control_effort: float = 0.0
    
    # Safety statistics
    total_safety_violations: int = 0
    safety_violation_rate: float = 0.0
    
    # Robustness metrics
    performance_consistency: float = 0.0  # 1 - CV of RMS error
    worst_case_error: float = 0.0
    
    # Controller-specific metrics
    controller_type: str = "unknown"
    training_time: float = 0.0
    convergence_generation: Optional[int] = None


class MetricsCollector:
    """Collects and computes metrics for TVC experiments"""
    
    def __init__(self, reference_trajectory_func=None):
        self.reference_func = reference_trajectory_func
        self.reset()
    
    def reset(self):
        """Reset collector for new episode"""
        self.time_history = []
        self.state_history = []
        self.action_history = []
        self.reference_history = []
        self.safety_violations = 0
        self.start_time = None
    
    def step(self, time: float, state: np.ndarray, action: np.ndarray, 
             reference: Optional[np.ndarray] = None):
        """Record data for one timestep"""
        
        if self.start_time is None:
            self.start_time = time
        
        self.time_history.append(time)
        self.state_history.append(state.copy())
        self.action_history.append(action.copy())
        
        # Generate or use provided reference
        if reference is not None:
            self.reference_history.append(reference.copy())
        elif self.reference_func is not None:
            ref = self.reference_func(time)
            self.reference_history.append(ref)
        else:
            # Default to zero reference
            self.reference_history.append(np.zeros_like(state))
        
        # Check for safety violations
        angle = state[0] if len(state) > 0 else 0.0
        rate = state[1] if len(state) > 1 else 0.0
        
        if abs(angle) > 0.785 or abs(rate) > 6.28:  # 45 degrees, 2π rad/s
            self.safety_violations += 1
    
    def finalize_episode(self, success: bool = True, 
                        termination_reason: str = "completed") -> EpisodeMetrics:
        """Compute metrics for completed episode"""
        
        if len(self.time_history) == 0:
            return EpisodeMetrics(
                time=np.array([]),
                states=np.array([]),
                actions=np.array([]),
                reference=np.array([]),
                success=False,
                termination_reason="no_data"
            )
        
        # Convert to arrays
        time = np.array(self.time_history)
        states = np.array(self.state_history)
        actions = np.array(self.action_history)
        reference = np.array(self.reference_history)
        
        # Compute performance metrics
        metrics = self._compute_performance_metrics(time, states, actions, reference)
        
        # Add episode info
        metrics.success = success
        metrics.termination_reason = termination_reason
        metrics.episode_length = len(time)
        metrics.safety_violations = self.safety_violations
        
        return metrics
    
    def _compute_performance_metrics(self, time: np.ndarray, states: np.ndarray,
                                   actions: np.ndarray, reference: np.ndarray) -> EpisodeMetrics:
        """Compute detailed performance metrics"""
        
        # Initialize metrics object
        metrics = EpisodeMetrics(
            time=time,
            states=states,
            actions=actions,
            reference=reference
        )
        
        if len(states) == 0:
            return metrics
        
        # Error computation
        if len(reference) == len(states):
            errors = states - reference
        else:
            # If reference is just angle, compare with angle state
            if reference.shape[-1] == 1 and states.shape[-1] >= 1:
                errors = states[:, [0]] - reference
            else:
                errors = states - reference
        
        angle_errors = errors[:, 0] if errors.shape[1] > 0 else errors.flatten()
        
        # RMS and max error
        metrics.rms_error = np.sqrt(np.mean(angle_errors**2))
        metrics.max_error = np.max(np.abs(angle_errors))
        
        # Settling time (time to reach and stay within 5% of final value)
        if len(angle_errors) > 1:
            final_error = np.mean(angle_errors[-10:])  # Last 10 points
            threshold = 0.05 * abs(final_error) if abs(final_error) > 1e-6 else 0.05
            
            settled_mask = np.abs(angle_errors - final_error) <= threshold
            settled_indices = np.where(settled_mask)[0]
            
            if len(settled_indices) > 0:
                # Find first index where it stays settled
                for i in settled_indices:
                    if i < len(settled_mask) - 10:  # Need at least 10 points remaining
                        if np.all(settled_mask[i:i+10]):  # Check next 10 points
                            metrics.settling_time = time[i] - time[0]
                            break
        
        # Overshoot
        if len(reference) > 0 and len(angle_errors) > 0:
            target = reference[-1, 0] if reference.ndim > 1 else reference[-1]
            if isinstance(target, (list, np.ndarray)):
                target = target[0] if len(target) > 0 else 0.0
            
            peak_error = np.max(np.abs(angle_errors))
            steady_state_error = np.abs(angle_errors[-1])
            metrics.overshoot = max(0, peak_error - steady_state_error)
        
        # Safety violations
        angles = states[:, 0] if states.shape[1] > 0 else states.flatten()
        rates = states[:, 1] if states.shape[1] > 1 else np.zeros_like(angles)
        
        angle_violations = np.abs(angles) > 0.785  # 45 degrees
        rate_violations = np.abs(rates) > 6.28     # 2π rad/s
        
        metrics.max_angle_violation = np.max(np.abs(angles)) - 0.785
        metrics.max_rate_violation = np.max(np.abs(rates)) - 6.28
        metrics.max_angle_violation = max(0, metrics.max_angle_violation)
        metrics.max_rate_violation = max(0, metrics.max_rate_violation)
        
        # Control effort metrics
        if len(actions) > 0:
            control_magnitudes = np.abs(actions.flatten())
            metrics.total_control_effort = np.sum(control_magnitudes)
            metrics.max_control_effort = np.max(control_magnitudes)
            
            # Control smoothness (negative of total variation)
            if len(actions) > 1:
                control_diff = np.diff(actions.flatten())
                metrics.control_smoothness = -np.sum(np.abs(control_diff))
                
                # Motor jerk (derivative of control effort)
                if len(control_diff) > 1:
                    dt = np.mean(np.diff(time))
                    jerk = np.diff(control_diff) / dt
                    metrics.motor_jerk = np.sqrt(np.mean(jerk**2))
        
        # Energy consumption (simplified)
        if len(actions) > 0 and len(time) > 1:
            dt = np.mean(np.diff(time))
            power = np.abs(actions.flatten())**2
            metrics.energy_consumption = np.sum(power) * dt
            
            # Fuel efficiency (distance per energy)
            if metrics.energy_consumption > 0:
                distance_traveled = np.sum(np.abs(np.diff(angles)))
                metrics.fuel_efficiency = distance_traveled / metrics.energy_consumption
        
        return metrics


class MetricsAnalyzer:
    """Analyzes and compares experimental results"""
    
    @staticmethod
    def compute_experiment_metrics(episodes: List[EpisodeMetrics], 
                                 controller_type: str = "unknown",
                                 training_time: float = 0.0) -> ExperimentMetrics:
        """Compute aggregate metrics from episode list"""
        
        if not episodes:
            return ExperimentMetrics(controller_type=controller_type)
        
        # Extract scalar metrics
        rms_errors = [ep.rms_error for ep in episodes]
        settling_times = [ep.settling_time for ep in episodes if ep.settling_time < np.inf]
        control_efforts = [ep.total_control_effort for ep in episodes]
        successes = [ep.success for ep in episodes]
        
        # Compute statistics
        exp_metrics = ExperimentMetrics(
            episodes=episodes,
            controller_type=controller_type,
            training_time=training_time
        )
        
        if rms_errors:
            exp_metrics.mean_rms_error = np.mean(rms_errors)
            exp_metrics.std_rms_error = np.std(rms_errors)
            exp_metrics.worst_case_error = np.max(rms_errors)
            
            # Performance consistency (1 - coefficient of variation)
            cv = exp_metrics.std_rms_error / exp_metrics.mean_rms_error if exp_metrics.mean_rms_error > 0 else 0
            exp_metrics.performance_consistency = max(0, 1 - cv)
        
        if settling_times:
            exp_metrics.mean_settling_time = np.mean(settling_times)
        
        if control_efforts:
            exp_metrics.mean_control_effort = np.mean(control_efforts)
        
        exp_metrics.success_rate = np.mean(successes) if successes else 0.0
        exp_metrics.total_safety_violations = sum(ep.safety_violations for ep in episodes)
        exp_metrics.safety_violation_rate = exp_metrics.total_safety_violations / len(episodes) if episodes else 0.0
        
        return exp_metrics
    
    @staticmethod
    def compare_experiments(experiments: Dict[str, ExperimentMetrics]) -> Dict[str, Any]:
        """Generate comprehensive comparison between experiments"""
        
        comparison = {
            'summary': {},
            'rankings': {},
            'statistical_tests': {},
            'recommendations': []
        }
        
        if not experiments:
            return comparison
        
        # Summary statistics
        for name, exp in experiments.items():
            comparison['summary'][name] = {
                'rms_error': f"{exp.mean_rms_error:.4f} ± {exp.std_rms_error:.4f}",
                'success_rate': f"{exp.success_rate:.2%}",
                'safety_violations': exp.total_safety_violations,
                'settling_time': f"{exp.mean_settling_time:.2f}s",
                'control_effort': f"{exp.mean_control_effort:.2f}",
                'consistency': f"{exp.performance_consistency:.3f}"
            }
        
        # Rankings
        metrics_to_rank = [
            ('rms_error', 'mean_rms_error', False),  # Lower is better
            ('success_rate', 'success_rate', True),   # Higher is better
            ('safety', 'safety_violation_rate', False),  # Lower is better
            ('consistency', 'performance_consistency', True),  # Higher is better
        ]
        
        for metric_name, attr_name, higher_better in metrics_to_rank:
            values = [(name, getattr(exp, attr_name)) for name, exp in experiments.items()]
            values.sort(key=lambda x: x[1], reverse=higher_better)
            comparison['rankings'][metric_name] = [name for name, _ in values]
        
        # Statistical significance tests
        if len(experiments) >= 2:
            exp_names = list(experiments.keys())
            for i, name1 in enumerate(exp_names):
                for name2 in exp_names[i+1:]:
                    exp1, exp2 = experiments[name1], experiments[name2]
                    
                    # Compare RMS errors using t-test
                    if exp1.episodes and exp2.episodes:
                        errors1 = [ep.rms_error for ep in exp1.episodes]
                        errors2 = [ep.rms_error for ep in exp2.episodes]
                        
                        if len(errors1) > 1 and len(errors2) > 1:
                            t_stat, p_value = stats.ttest_ind(errors1, errors2)
                            comparison['statistical_tests'][f"{name1}_vs_{name2}"] = {
                                't_statistic': t_stat,
                                'p_value': p_value,
                                'significant': p_value < 0.05
                            }
        
        # Generate recommendations
        best_overall = comparison['rankings'].get('rms_error', [None])[0]
        safest = comparison['rankings'].get('safety', [None])[0]
        most_consistent = comparison['rankings'].get('consistency', [None])[0]
        
        if best_overall:
            comparison['recommendations'].append(f"Best overall performance: {best_overall}")
        if safest and safest != best_overall:
            comparison['recommendations'].append(f"Safest controller: {safest}")
        if most_consistent and most_consistent not in [best_overall, safest]:
            comparison['recommendations'].append(f"Most consistent: {most_consistent}")
        
        return comparison
    
    @staticmethod
    def save_metrics(experiment_metrics: ExperimentMetrics, filepath: str):
        """Save experiment metrics to JSON file"""
        
        # Convert to serializable format
        data = {
            'controller_type': experiment_metrics.controller_type,
            'training_time': experiment_metrics.training_time,
            'mean_rms_error': experiment_metrics.mean_rms_error,
            'std_rms_error': experiment_metrics.std_rms_error,
            'success_rate': experiment_metrics.success_rate,
            'mean_settling_time': experiment_metrics.mean_settling_time,
            'mean_control_effort': experiment_metrics.mean_control_effort,
            'total_safety_violations': experiment_metrics.total_safety_violations,
            'safety_violation_rate': experiment_metrics.safety_violation_rate,
            'performance_consistency': experiment_metrics.performance_consistency,
            'worst_case_error': experiment_metrics.worst_case_error,
            'convergence_generation': experiment_metrics.convergence_generation,
            'num_episodes': len(experiment_metrics.episodes)
        }
        
        # Create directory if needed
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)


def test_metrics_system():
    """Test metrics collection and analysis"""
    print("Testing Metrics System")
    print("=" * 40)
    
    # Create test data
    np.random.seed(42)
    
    collector = MetricsCollector()
    
    # Simulate an episode
    time_steps = np.linspace(0, 5, 100)
    for i, t in enumerate(time_steps):
        # Simulate decaying oscillation
        angle = 0.5 * np.exp(-0.5*t) * np.cos(2*t) + 0.01*np.random.randn()
        rate = -0.25 * np.exp(-0.5*t) * (np.cos(2*t) + 4*np.sin(2*t)) + 0.01*np.random.randn()
        state = np.array([angle, rate])
        
        # Simple control action
        action = np.array([-2*angle - 0.5*rate + 0.1*np.random.randn()])
        
        reference = np.array([0.0, 0.0])
        
        collector.step(t, state, action, reference)
    
    # Finalize episode
    episode_metrics = collector.finalize_episode(success=True)
    
    print(f"Episode RMS error: {episode_metrics.rms_error:.4f}")
    print(f"Episode settling time: {episode_metrics.settling_time:.2f}s")
    print(f"Episode success: {episode_metrics.success}")
    print(f"Safety violations: {episode_metrics.safety_violations}")
    
    # Test experiment metrics
    episodes = [episode_metrics] * 10  # Simulate 10 identical episodes
    exp_metrics = MetricsAnalyzer.compute_experiment_metrics(
        episodes, controller_type="test_controller"
    )
    
    print(f"Experiment success rate: {exp_metrics.success_rate:.2%}")
    print(f"Mean RMS error: {exp_metrics.mean_rms_error:.4f}")
    
    # Test comparison
    experiments = {
        'controller_a': exp_metrics,
        'controller_b': exp_metrics  # Same metrics for test
    }
    
    comparison = MetricsAnalyzer.compare_experiments(experiments)
    print(f"Comparison rankings: {comparison['rankings']}")
    
    print("Metrics system test completed!")


if __name__ == "__main__":
    test_metrics_system()