"""
Visualization utilities for TVC experiments

This module provides comprehensive plotting and visualization capabilities
for analyzing TVC controller performance and comparing experimental results.

Author: Generated by GitHub Copilot
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.patches import Rectangle, Polygon
import seaborn as sns
from typing import Dict, List, Optional, Tuple, Any
import pandas as pd
from pathlib import Path
import matplotlib.animation as animation

from .metrics import EpisodeMetrics, ExperimentMetrics


# Set style
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")


class TVCVisualizer:
    """Comprehensive visualization for TVC experiments"""
    
    def __init__(self, save_dir: str = "./plots"):
        self.save_dir = Path(save_dir)
        self.save_dir.mkdir(parents=True, exist_ok=True)
        
        # Color scheme for different controllers
        self.colors = {
            'mpc_baseline': '#1f77b4',
            'safe_mpc': '#17becf',
            # Legacy keys for backward compatibility
            'lqr': '#1f77b4',
            'safe_lqr': '#17becf',
            'evolution': '#ff7f0e', 
            'safe_evolution': '#2ca02c',
            'residual_ppo': '#d62728',
            'safe_residual_ppo': '#9467bd',
            'baseline': '#8c564b'
        }
    
    def plot_trajectory(self, episode: EpisodeMetrics, title: str = "TVC Trajectory",
                       save_name: Optional[str] = None) -> Figure:
        """Plot single episode trajectory"""
        
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle(title, fontsize=16)
        
        time = episode.time
        states = episode.states
        actions = episode.actions
        reference = episode.reference
        
        # Angle trajectory
        axes[0, 0].plot(time, states[:, 0], 'b-', label='Actual', linewidth=2)
        if len(reference) > 0:
            ref_angle = reference[:, 0] if reference.ndim > 1 else reference
            axes[0, 0].plot(time, ref_angle, 'r--', label='Reference', linewidth=2)
        axes[0, 0].axhline(y=0.785, color='red', linestyle=':', alpha=0.7, label='Safety limit')
        axes[0, 0].axhline(y=-0.785, color='red', linestyle=':', alpha=0.7)
        axes[0, 0].set_ylabel('Angle (rad)')
        axes[0, 0].set_title('Attitude Trajectory')
        axes[0, 0].legend()
        axes[0, 0].grid(True, alpha=0.3)
        
        # Angular rate
        if states.shape[1] > 1:
            axes[0, 1].plot(time, states[:, 1], 'g-', linewidth=2)
            axes[0, 1].axhline(y=6.28, color='red', linestyle=':', alpha=0.7, label='Safety limit')
            axes[0, 1].axhline(y=-6.28, color='red', linestyle=':', alpha=0.7)
        axes[0, 1].set_ylabel('Angular Rate (rad/s)')
        axes[0, 1].set_title('Angular Rate')
        axes[0, 1].legend()
        axes[0, 1].grid(True, alpha=0.3)
        
        # Control action
        if len(actions) > 0:
            control = actions.flatten()
            axes[1, 0].plot(time, control, 'm-', linewidth=2)
            axes[1, 0].axhline(y=0.524, color='red', linestyle=':', alpha=0.7, label='Actuator limit')
            axes[1, 0].axhline(y=-0.524, color='red', linestyle=':', alpha=0.7)
        axes[1, 0].set_ylabel('Control Input (rad)')
        axes[1, 0].set_xlabel('Time (s)')
        axes[1, 0].set_title('Control Action')
        axes[1, 0].legend()
        axes[1, 0].grid(True, alpha=0.3)
        
        # Phase portrait
        if states.shape[1] > 1:
            axes[1, 1].plot(states[:, 0], states[:, 1], 'b-', linewidth=2)
            axes[1, 1].plot(states[0, 0], states[0, 1], 'go', markersize=8, label='Start')
            axes[1, 1].plot(states[-1, 0], states[-1, 1], 'ro', markersize=8, label='End')
            
            # Safety boundaries
            theta = np.linspace(0, 2*np.pi, 100)
            safety_angle = 0.785
            safety_rate = 6.28
            boundary_x = safety_angle * np.cos(theta)
            boundary_y = safety_rate * np.sin(theta)
            axes[1, 1].plot(boundary_x, boundary_y, 'r:', alpha=0.7, label='Safety boundary')
        
        axes[1, 1].set_xlabel('Angle (rad)')
        axes[1, 1].set_ylabel('Angular Rate (rad/s)')
        axes[1, 1].set_title('Phase Portrait')
        axes[1, 1].legend()
        axes[1, 1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_name:
            plt.savefig(self.save_dir / f"{save_name}.png", dpi=300, bbox_inches='tight')
        
        return fig
    
    def plot_comparison_trajectories(self, episodes: Dict[str, EpisodeMetrics], 
                                   title: str = "Controller Comparison",
                                   save_name: Optional[str] = None) -> Figure:
        """Plot trajectories from multiple controllers"""
        
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle(title, fontsize=16)
        
        for name, episode in episodes.items():
            color = self.colors.get(name, np.random.rand(3,))
            time = episode.time
            states = episode.states
            actions = episode.actions
            
            # Angle trajectories
            axes[0, 0].plot(time, states[:, 0], color=color, label=name, linewidth=2)
            
            # Angular rates
            if states.shape[1] > 1:
                axes[0, 1].plot(time, states[:, 1], color=color, label=name, linewidth=2)
            
            # Control actions
            if len(actions) > 0:
                axes[1, 0].plot(time, actions.flatten(), color=color, label=name, linewidth=2)
            
            # Phase portraits
            if states.shape[1] > 1:
                axes[1, 1].plot(states[:, 0], states[:, 1], color=color, label=name, linewidth=2)
        
        # Add safety limits and formatting
        axes[0, 0].axhline(y=0.785, color='red', linestyle=':', alpha=0.7)
        axes[0, 0].axhline(y=-0.785, color='red', linestyle=':', alpha=0.7)
        axes[0, 0].set_ylabel('Angle (rad)')
        axes[0, 0].set_title('Attitude Comparison')
        axes[0, 0].legend()
        axes[0, 0].grid(True, alpha=0.3)
        
        axes[0, 1].axhline(y=6.28, color='red', linestyle=':', alpha=0.7)
        axes[0, 1].axhline(y=-6.28, color='red', linestyle=':', alpha=0.7)
        axes[0, 1].set_ylabel('Angular Rate (rad/s)')
        axes[0, 1].set_title('Rate Comparison')
        axes[0, 1].legend()
        axes[0, 1].grid(True, alpha=0.3)
        
        axes[1, 0].axhline(y=0.524, color='red', linestyle=':', alpha=0.7)
        axes[1, 0].axhline(y=-0.524, color='red', linestyle=':', alpha=0.7)
        axes[1, 0].set_ylabel('Control Input (rad)')
        axes[1, 0].set_xlabel('Time (s)')
        axes[1, 0].set_title('Control Comparison')
        axes[1, 0].legend()
        axes[1, 0].grid(True, alpha=0.3)
        
        axes[1, 1].set_xlabel('Angle (rad)')
        axes[1, 1].set_ylabel('Angular Rate (rad/s)')
        axes[1, 1].set_title('Phase Portrait Comparison')
        axes[1, 1].legend()
        axes[1, 1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_name:
            plt.savefig(self.save_dir / f"{save_name}.png", dpi=300, bbox_inches='tight')
        
        return fig
    
    def plot_experiment_metrics(self, experiments: Dict[str, ExperimentMetrics],
                              save_name: Optional[str] = None) -> Figure:
        """Plot aggregate metrics comparison"""
        
        fig, axes = plt.subplots(2, 3, figsize=(18, 12))
        fig.suptitle('Experiment Metrics Comparison', fontsize=16)
        
        names = list(experiments.keys())
        colors = [self.colors.get(name, np.random.rand(3,)) for name in names]
        
        # RMS Error comparison
        rms_means = [exp.mean_rms_error for exp in experiments.values()]
        rms_stds = [exp.std_rms_error for exp in experiments.values()]
        
        bars1 = axes[0, 0].bar(names, rms_means, yerr=rms_stds, capsize=5, color=colors, alpha=0.7)
        axes[0, 0].set_ylabel('RMS Error (rad)')
        axes[0, 0].set_title('RMS Error Comparison')
        axes[0, 0].tick_params(axis='x', rotation=45)
        axes[0, 0].grid(True, alpha=0.3)
        
        # Success rate
        success_rates = [exp.success_rate * 100 for exp in experiments.values()]
        bars2 = axes[0, 1].bar(names, success_rates, color=colors, alpha=0.7)
        axes[0, 1].set_ylabel('Success Rate (%)')
        axes[0, 1].set_title('Success Rate Comparison')
        axes[0, 1].set_ylim(0, 105)
        axes[0, 1].tick_params(axis='x', rotation=45)
        axes[0, 1].grid(True, alpha=0.3)
        
        # Safety violations
        safety_violations = [exp.total_safety_violations for exp in experiments.values()]
        bars3 = axes[0, 2].bar(names, safety_violations, color=colors, alpha=0.7)
        axes[0, 2].set_ylabel('Total Safety Violations')
        axes[0, 2].set_title('Safety Performance')
        axes[0, 2].tick_params(axis='x', rotation=45)
        axes[0, 2].grid(True, alpha=0.3)
        
        # Settling time
        settling_times = [exp.mean_settling_time for exp in experiments.values()]
        bars4 = axes[1, 0].bar(names, settling_times, color=colors, alpha=0.7)
        axes[1, 0].set_ylabel('Settling Time (s)')
        axes[1, 0].set_title('Settling Time Comparison')
        axes[1, 0].tick_params(axis='x', rotation=45)
        axes[1, 0].grid(True, alpha=0.3)
        
        # Control effort
        control_efforts = [exp.mean_control_effort for exp in experiments.values()]
        bars5 = axes[1, 1].bar(names, control_efforts, color=colors, alpha=0.7)
        axes[1, 1].set_ylabel('Control Effort')
        axes[1, 1].set_title('Control Effort Comparison')
        axes[1, 1].tick_params(axis='x', rotation=45)
        axes[1, 1].grid(True, alpha=0.3)
        
        # Performance consistency
        consistency = [exp.performance_consistency for exp in experiments.values()]
        bars6 = axes[1, 2].bar(names, consistency, color=colors, alpha=0.7)
        axes[1, 2].set_ylabel('Performance Consistency')
        axes[1, 2].set_title('Consistency Comparison')
        axes[1, 2].set_ylim(0, 1.1)
        axes[1, 2].tick_params(axis='x', rotation=45)
        axes[1, 2].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_name:
            plt.savefig(self.save_dir / f"{save_name}.png", dpi=300, bbox_inches='tight')
        
        return fig
    
    def plot_training_curves(self, training_data: Dict[str, Dict[str, List[float]]],
                           save_name: Optional[str] = None) -> Figure:
        """Plot training progression curves"""
        
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))
        fig.suptitle('Training Progress', fontsize=16)
        
        for method_name, data in training_data.items():
            color = self.colors.get(method_name, np.random.rand(3,))
            
            # Fitness/reward evolution
            if 'fitness' in data:
                generations = range(len(data['fitness']))
                axes[0, 0].plot(generations, data['fitness'], color=color, 
                              label=method_name, linewidth=2)
            elif 'rewards' in data:
                episodes = range(len(data['rewards']))
                axes[0, 0].plot(episodes, data['rewards'], color=color,
                              label=method_name, linewidth=2)
            
            # Loss evolution (for gradient-based methods)
            if 'loss' in data:
                episodes = range(len(data['loss']))
                axes[0, 1].plot(episodes, data['loss'], color=color,
                              label=method_name, linewidth=2)
            
            # Success rate evolution
            if 'success_rate' in data:
                episodes = range(len(data['success_rate']))
                axes[1, 0].plot(episodes, data['success_rate'], color=color,
                              label=method_name, linewidth=2)
            
            # Population diversity (for evolutionary methods)
            if 'diversity' in data:
                generations = range(len(data['diversity']))
                axes[1, 1].plot(generations, data['diversity'], color=color,
                              label=method_name, linewidth=2)
        
        # Format subplots
        axes[0, 0].set_ylabel('Fitness/Reward')
        axes[0, 0].set_xlabel('Generation/Episode')
        axes[0, 0].set_title('Fitness Evolution')
        axes[0, 0].legend()
        axes[0, 0].grid(True, alpha=0.3)
        
        axes[0, 1].set_ylabel('Loss')
        axes[0, 1].set_xlabel('Episode')
        axes[0, 1].set_title('Training Loss')
        axes[0, 1].legend()
        axes[0, 1].grid(True, alpha=0.3)
        
        axes[1, 0].set_ylabel('Success Rate')
        axes[1, 0].set_xlabel('Episode')
        axes[1, 0].set_title('Success Rate Evolution')
        axes[1, 0].legend()
        axes[1, 0].grid(True, alpha=0.3)
        
        axes[1, 1].set_ylabel('Population Diversity')
        axes[1, 1].set_xlabel('Generation')
        axes[1, 1].set_title('Population Diversity')
        axes[1, 1].legend()
        axes[1, 1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_name:
            plt.savefig(self.save_dir / f"{save_name}.png", dpi=300, bbox_inches='tight')
        
        return fig
    
    def plot_error_distributions(self, experiments: Dict[str, ExperimentMetrics],
                               save_name: Optional[str] = None) -> Figure:
        """Plot error distribution comparison"""
        
        fig, axes = plt.subplots(1, 2, figsize=(15, 6))
        fig.suptitle('Error Distribution Analysis', fontsize=16)
        
        # Collect all RMS errors
        all_errors = {}
        for name, exp in experiments.items():
            errors = [ep.rms_error for ep in exp.episodes]
            all_errors[name] = errors
        
        # Box plot
        box_data = [errors for errors in all_errors.values()]
        box_labels = list(all_errors.keys())
        
        bp = axes[0].boxplot(box_data, labels=box_labels, patch_artist=True)
        for patch, name in zip(bp['boxes'], box_labels):
            color = self.colors.get(name, np.random.rand(3,))
            patch.set_facecolor(color)
            patch.set_alpha(0.7)
        
        axes[0].set_ylabel('RMS Error (rad)')
        axes[0].set_title('Error Distribution (Box Plot)')
        axes[0].tick_params(axis='x', rotation=45)
        axes[0].grid(True, alpha=0.3)
        
        # Histogram
        for name, errors in all_errors.items():
            color = self.colors.get(name, np.random.rand(3,))
            axes[1].hist(errors, bins=20, alpha=0.6, label=name, 
                        color=color, density=True)
        
        axes[1].set_xlabel('RMS Error (rad)')
        axes[1].set_ylabel('Density')
        axes[1].set_title('Error Distribution (Histogram)')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_name:
            plt.savefig(self.save_dir / f"{save_name}.png", dpi=300, bbox_inches='tight')
        
        return fig
    
    def create_animation(self, episode: EpisodeMetrics, save_name: Optional[str] = None,
                        interval: int = 50) -> animation.FuncAnimation:
        """Create animation of TVC vehicle motion"""
        
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
        
        time = episode.time
        states = episode.states
        actions = episode.actions
        
        # Vehicle visualization
        ax1.set_xlim(-2, 2)
        ax1.set_ylim(-1, 3)
        ax1.set_aspect('equal')
        ax1.set_title('TVC Vehicle Animation')
        ax1.grid(True, alpha=0.3)
        
        # Vehicle body (rectangle)
        vehicle_body = Rectangle((-0.1, 0), 0.2, 1.0, color='blue', alpha=0.7)
        ax1.add_patch(vehicle_body)
        
        # Nozzle (triangle)
        nozzle = Polygon([(-0.05, 0), (0.05, 0), (0, -0.2)], color='red', alpha=0.7)
        ax1.add_patch(nozzle)
        
        # Thrust vector
        thrust_line, = ax1.plot([], [], 'r-', linewidth=3)
        
        # Angle trace
        angle_trace, = ax2.plot([], [], 'b-', linewidth=2, label='Angle')
        action_trace, = ax2.plot([], [], 'r-', linewidth=2, label='Control')
        
        ax2.set_xlim(0, time[-1])
        ax2.set_ylim(-1, 1)
        ax2.set_xlabel('Time (s)')
        ax2.set_ylabel('Angle/Control (rad)')
        ax2.set_title('System Response')
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        
        def animate(frame):
            if frame >= len(states):
                return vehicle_body, nozzle, thrust_line, angle_trace, action_trace
            
            # Get current state
            angle = states[frame, 0]
            control = actions[frame, 0] if frame < len(actions) else 0
            
            # Update vehicle orientation
            cos_a, sin_a = np.cos(angle), np.sin(angle)
            
            # Rotate vehicle body
            vehicle_body.set_xy((-0.1*cos_a - 0*sin_a, -0.1*sin_a + 0*cos_a))
            vehicle_body.angle = np.degrees(angle)
            
            # Update nozzle position and orientation
            nozzle_points = np.array([[-0.05, 0.05, 0], [0, 0, -0.2]])
            rotation_matrix = np.array([[cos_a, -sin_a], [sin_a, cos_a]])
            rotated_nozzle = rotation_matrix @ nozzle_points
            
            nozzle.set_xy(rotated_nozzle.T)
            
            # Update thrust vector
            thrust_length = abs(control) * 0.5
            thrust_angle = angle + control
            thrust_x = [0, thrust_length * np.sin(thrust_angle)]
            thrust_y = [-0.2, -0.2 - thrust_length * np.cos(thrust_angle)]
            thrust_line.set_data(thrust_x, thrust_y)
            
            # Update traces
            current_time = time[:frame+1]
            current_angles = states[:frame+1, 0]
            current_actions = actions[:frame+1, 0] if frame < len(actions) else actions[:, 0]
            
            angle_trace.set_data(current_time, current_angles)
            action_trace.set_data(current_time, current_actions[:len(current_time)])
            
            return vehicle_body, nozzle, thrust_line, angle_trace, action_trace
        
        anim = animation.FuncAnimation(fig, animate, frames=len(states), interval=interval, blit=False, repeat=True)
        
        if save_name:
            anim.save(self.save_dir / f"{save_name}.gif", writer='pillow', fps=20)
        
        return anim


def test_visualization():
    """Test visualization system"""
    print("Testing Visualization System")
    print("=" * 40)
    
    # Create test data
    np.random.seed(42)
    visualizer = TVCVisualizer(save_dir="./test_plots")
    
    # Generate test episode
    time = np.linspace(0, 5, 100)
    states = np.zeros((100, 2))
    actions = np.zeros((100, 1))
    
    for i, t in enumerate(time):
        angle = 0.5 * np.exp(-0.5*t) * np.cos(2*t)
        rate = -0.25 * np.exp(-0.5*t) * (np.cos(2*t) + 4*np.sin(2*t))
        states[i] = [angle, rate]
        actions[i] = [-2*angle - 0.5*rate]
    
    # Create test episode metrics
    episode = EpisodeMetrics(
        time=time,
        states=states,
        actions=actions,
        reference=np.zeros((100, 2)),
        rms_error=0.1,
        success=True
    )
    
    # Test trajectory plot
    fig1 = visualizer.plot_trajectory(episode, title="Test Trajectory")
    print("✓ Trajectory plot created")
    
    # Test comparison plot
    episodes = {'controller_a': episode, 'controller_b': episode}
    fig2 = visualizer.plot_comparison_trajectories(episodes)
    print("✓ Comparison plot created")
    
    # Test metrics plot
    from .metrics import ExperimentMetrics
    exp_metrics = ExperimentMetrics(
        episodes=[episode] * 5,
        controller_type="test",
        mean_rms_error=0.1,
        success_rate=1.0
    )
    
    experiments = {'test_controller': exp_metrics}
    fig3 = visualizer.plot_experiment_metrics(experiments)
    print("✓ Metrics plot created")
    
    plt.close('all')  # Close all figures
    print("Visualization system test completed!")
