#!/usr/bin/env python3
"""
Evaluation script for TVC controllers

This script provides a command-line interface for evaluating and comparing
different TVC controllers with comprehensive analysis and visualization.

Usage:
    python evaluate.py --experiment comparison
    python evaluate.py --config configs/comparison.yaml
    python evaluate.py --quick-test

Author: Generated by GitHub Copilot
"""

import argparse
import sys
from pathlib import Path

# Add src to path - ensure we can find the src directory
script_dir = Path(__file__).parent
project_root = script_dir.parent
src_path = project_root / "src"

if src_path.exists():
    sys.path.insert(0, str(project_root))
else:
    raise ImportError(f"Source directory not found at {src_path}")

from src.evaluation import ControllerEvaluator, run_comparison_experiment, test_evaluation_framework
from src.utils import create_config_object
import yaml
from typing import Dict, Any, Optional

# Simple config loading utility
def load_yaml_config(config_path: str) -> Dict[str, Any]:
    """Load YAML configuration file with error handling"""
    try:
        config_file = Path(config_path)
        if not config_file.exists():
            # Try relative path from script location
            script_dir = Path(__file__).parent
            relative_config = script_dir / config_path
            if relative_config.exists():
                config_file = relative_config
            else:
                # Try looking in configs directory
                configs_config = script_dir.parent / "configs" / Path(config_path).name
                if configs_config.exists():
                    config_file = configs_config
                else:
                    raise FileNotFoundError(f"Configuration file not found: {config_path}")
        
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)
            
        if not isinstance(config, dict):
            raise ValueError(f"Configuration file must contain a dictionary, got {type(config)}")
            
        print(f"Successfully loaded configuration from: {config_file}")
        return config
        
    except yaml.YAMLError as e:
        raise ValueError(f"Invalid YAML syntax in {config_path}: {e}")
    except Exception as e:
        raise RuntimeError(f"Failed to load configuration from {config_path}: {e}")

# Default configuration fallback
def get_default_config() -> Dict[str, Any]:
    """Get default configuration values"""
    return {
        'experiment_name': 'default_evaluation',
        'output_dir': 'results',
        'use_safety_filter': True,
        'eval_episodes': 100,
        'plant': {
            'mass': 1000.0,
            'length': 10.0,
            'inertia': 8333.33,
            'thrust_max': 15000.0,
            'gimbal_limit': 0.2617993877991494,
            'gravity': 9.81,
            'dt': 0.01
        },
        'evolution': {
            'population_size': 200,
            'max_generations': 100,
            'sim_duration': 20.0,
            'mutation_rate': 0.1,
            'elite_ratio': 0.1,
            'tournament_size': 5
        },
        'ppo': {
            'total_frames': 1000000,
            'frames_per_batch': 4096,
            'lr_actor': 0.0003,
            'lr_critic': 0.001,
            'gamma': 0.99,
            'clip_epsilon': 0.2,
            'value_loss_coef': 0.5,
            'entropy_coef': 0.01
        },
        'lqr': {
            'Q': [[100, 0, 0, 0], [0, 100, 0, 0], [0, 0, 10, 0], [0, 0, 0, 10]],
            'R': [[1, 0], [0, 1]]
        },
        'safety': {
            'max_velocity': 50.0,
            'max_angle': 0.785398,
            'barrier_alpha': 1.0,
            'lyapunov_eps': 0.1
        }
    }

# Available predefined experiments (matching our config files)
def get_available_experiments() -> Dict[str, str]:
    """Get available predefined experiment configurations"""
    return {
        'default': '../configs/default.yaml',
        'small_rocket': '../configs/small_rocket.yaml',
        'large_rocket': '../configs/large_rocket.yaml',
        'high_performance': '../configs/high_performance.yaml',
        'quick_test': '../configs/quick_test.yaml',
        'safety_focused': '../configs/safety_focused.yaml',
        'evolution_only': '../configs/evolution_only.yaml',
        'ppo_only': '../configs/ppo_only.yaml',
        'comparison': '../configs/comparison.yaml',
        'aggressive_rocket': '../configs/aggressive_rocket.yaml',
        'windy_environment': '../configs/windy_environment.yaml',
        'heavy_payload': '../configs/heavy_payload.yaml',
        'precision_landing': '../configs/precision_landing.yaml',
        'development': '../configs/development.yaml'
    }


def run_evaluation(experiment_name: Optional[str] = None, config_path: Optional[str] = None):
    """Run evaluation experiment"""
    
    # Load configuration
    if config_path:
        try:
            config_dict = load_yaml_config(config_path)
            config = create_config_object(config_dict)
            experiment_name_attr = getattr(config, 'experiment_name', 'evaluation')
            print(f"Using configuration: {experiment_name_attr}")
        except Exception as e:
            print(f"Error loading configuration: {e}")
            print("Falling back to default configuration...")
            config_dict = get_default_config()
            config_dict['experiment_name'] = "default_evaluation"
            config = create_config_object(config_dict)
    elif experiment_name:
        # Use predefined experiment
        available_experiments = get_available_experiments()
        if experiment_name in available_experiments:
            config_path = available_experiments[experiment_name]
            try:
                config_dict = load_yaml_config(config_path)
                config = create_config_object(config_dict)
                print(f"Using predefined experiment: {experiment_name}")
            except Exception as e:
                print(f"Error loading experiment configuration: {e}")
                print("Falling back to default configuration...")
                config_dict = get_default_config()
                config_dict['experiment_name'] = f"{experiment_name}_evaluation"
                config = create_config_object(config_dict)
        else:
            print(f"Unknown experiment: {experiment_name}")
            print(f"Available experiments: {list(available_experiments.keys())}")
            return None
    else:
        # Default configuration
        config_dict = get_default_config()
        config_dict['experiment_name'] = "default_evaluation"
        config = create_config_object(config_dict)
        print("Using default configuration")
    
    # Run evaluation using create_default_config since ControllerEvaluator expects ExperimentConfig
    from src.utils.config import create_default_config
    default_config = create_default_config()
    evaluator = ControllerEvaluator(default_config)
    results = evaluator.run_complete_evaluation()
    
    return results, evaluator


def run_quick_test():
    """Run quick test of evaluation framework"""
    print("Running quick evaluation test...")
    test_evaluation_framework()
    print("Quick test completed!")


def run_comparison():
    """Run full comparison experiment"""
    print("Running comprehensive controller comparison...")
    results, evaluator = run_comparison_experiment()
    return results, evaluator


def analyze_existing_results(results_dir: str):
    """Analyze existing experimental results"""
    results_path = Path(results_dir)
    
    if not results_path.exists():
        print(f"Results directory not found: {results_dir}")
        return
    
    print(f"Analyzing results in {results_dir}...")
    
    # Look for result files
    result_files = list(results_path.glob("*_metrics.json"))
    
    if not result_files:
        print("No metrics files found in results directory")
        return
    
    # Load and display results
    import json
    from src.utils import MetricsAnalyzer
    
    experiments = {}
    
    for file_path in result_files:
        controller_name = file_path.stem.replace('_metrics', '')
        
        with open(file_path, 'r') as f:
            data = json.load(f)
        
        print(f"\n{controller_name.upper()}:")
        print(f"  RMS Error: {data.get('mean_rms_error', 'N/A'):.4f} ± {data.get('std_rms_error', 'N/A'):.4f}")
        print(f"  Success Rate: {data.get('success_rate', 'N/A'):.2%}")
        print(f"  Safety Violations: {data.get('total_safety_violations', 'N/A')}")
        print(f"  Training Time: {data.get('training_time', 'N/A'):.2f}s")
    
    print(f"\nFound results for {len(result_files)} controllers")


def list_available_configs():
    """List all available configuration files"""
    configs_dir = Path(__file__).parent.parent / "configs"
    
    if configs_dir.exists():
        print("Available configuration files:")
        print("="*50)
        yaml_files = list(configs_dir.glob("*.yaml"))
        
        if yaml_files:
            for config_file in sorted(yaml_files):
                print(f"  {config_file.name}")
                
                # Try to load and show brief description
                try:
                    with open(config_file, 'r') as f:
                        config = yaml.safe_load(f)
                        if isinstance(config, dict) and 'description' in config:
                            print(f"    Description: {config['description']}")
                        elif isinstance(config, dict) and 'experiment_name' in config:
                            print(f"    Experiment: {config['experiment_name']}")
                        print()
                except Exception:
                    print()
                    
            print(f"Usage: python evaluate.py --config ../configs/<config_name>.yaml")
        else:
            print("  No configuration files found")
    else:
        print(f"Configuration directory not found: {configs_dir}")
        print("Please ensure you're running from the scripts/ directory.")


def create_example_configs():
    """List available configuration files for evaluation"""
    configs_dir = Path(__file__).parent.parent / "configs"
    
    if configs_dir.exists():
        print(f"Configuration files available in {configs_dir}/")
        print("Use --list-configs to see all available configurations")
    else:
        print(f"Configuration directory not found: {configs_dir}")
        print("Please run the script from the scripts/ directory.")


def list_available_experiments():
    """List available predefined experiments"""
    available_experiments = get_available_experiments()
    
    print("Available predefined experiments:")
    print("="*40)
    
    for name, config_path in available_experiments.items():
        if Path(config_path).exists():
            try:
                config_dict = load_yaml_config(config_path)
                print(f"\n{name}:")
                print(f"  Config file: {config_path}")
                print(f"  Description: {config_dict.get('experiment_name', 'N/A')}")
                print(f"  Episodes: {config_dict.get('eval_episodes', 'N/A')}")
                print(f"  Safety filter: {config_dict.get('use_safety_filter', 'N/A')}")
                if 'evolution' in config_dict:
                    print(f"  Evolution population: {config_dict['evolution'].get('population_size', 'N/A')}")
                if 'ppo' in config_dict:
                    frames = config_dict['ppo'].get('total_frames', 0)
                    print(f"  PPO frames: {frames:,}")
            except Exception as e:
                print(f"\n{name}: Error loading config - {e}")
        else:
            print(f"\n{name}: Config file not found - {config_path}")


def main():
    """Main evaluation script entry point"""
    parser = argparse.ArgumentParser(description='Evaluate TVC Controllers')
    
    parser.add_argument('--experiment', type=str,
                       help='Predefined experiment to run (see --list for options)')
    parser.add_argument('--config', type=str,
                       help='Path to configuration file (e.g., ../configs/default.yaml)')
    parser.add_argument('--quick-test', action='store_true',
                       help='Run quick test of evaluation framework')
    parser.add_argument('--comparison', action='store_true',
                       help='Run comprehensive comparison experiment')
    parser.add_argument('--analyze', type=str,
                       help='Analyze existing results in specified directory')
    parser.add_argument('--create-configs', action='store_true',
                       help='List available configuration files')
    parser.add_argument('--list-configs', action='store_true',
                       help='List all available configuration files')
    parser.add_argument('--list', action='store_true',
                       help='List available predefined experiments')
    
    args = parser.parse_args()
    
    # Handle different modes
    if args.list:
        list_available_experiments()
        return
    
    if args.list_configs:
        list_available_configs()
        return
    
    if args.create_configs:
        create_example_configs()
        return
    
    if args.analyze:
        analyze_existing_results(args.analyze)
        return
    
    if args.quick_test:
        run_quick_test()
        return
    
    if args.comparison:
        run_comparison()
        return
    
    # Standard evaluation
    if args.experiment or args.config:
        result = run_evaluation(args.experiment, args.config)
        if result is not None:
            results, evaluator = result
            print(f"\nEvaluation completed successfully!")
            print(f"Results saved to: {evaluator.config.output_dir}")
        else:
            print("Evaluation failed!")
    else:
        # Default: run comparison
        print("No specific evaluation specified, running comparison experiment...")
        run_comparison()
    
    print("\nEvaluation script completed!")


if __name__ == "__main__":
    main()