#!/usr/bin/env python3
"""
Quick test script for TVC system

This script provides quick tests to verify that all components
of the TVC system are working correctly.

Usage:
    python test_system.py
    python test_system.py --component dynamics
    python test_system.py --component control
    python test_system.py --quick

Author: Generated by GitHub Copilot
"""

import argparse
import sys
import time
from pathlib import Path

# Add src to path
sys.path.append(str(Path(__file__).parent / "src"))

def test_imports():
    """Test that all imports work correctly"""
    print("Testing imports...")
    
    try:
        # Core components
        from src.dynamics import TVCPlant, TVCParameters
        from src.control import LQRController, CLFCBFQPFilter, LQRParameters, SafetyParameters
        from src.learning import (
            EvolutionaryTrainer, ResidualPPOTrainer, 
            SimpleControlNetwork, ResidualPolicyNetwork,
            EvolutionParameters, PPOParameters
        )
        from src.simulation import TVCMuJoCoEnv, MuJoCoSimParams
        from src.utils import (
            ExperimentConfig, create_default_config, 
            MetricsCollector, TVCVisualizer
        )
        from src.evaluation import ControllerEvaluator
        
        print("  ✓ All imports successful")
        return True
        
    except ImportError as e:
        print(f"  ✗ Import failed: {e}")
        return False


def test_dynamics():
    """Test dynamics components"""
    print("Testing dynamics...")
    
    try:
        from src.dynamics import test_tvc_plant
        test_tvc_plant()
        print("  ✓ Dynamics test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Dynamics test failed: {e}")
        return False


def test_control():
    """Test control components"""
    print("Testing control...")
    
    try:
        from src.control.lqr import test_lqr_controller
        from src.control.safety import test_clf_cbf_qp_filter
        
        test_lqr_controller()
        test_clf_cbf_qp_filter()
        print("  ✓ Control test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Control test failed: {e}")
        return False


def test_learning():
    """Test learning components"""
    print("Testing learning...")
    
    try:
        from src.learning.networks import test_networks
        from src.learning.evolution import test_evolutionary_trainer
        
        test_networks()
        test_evolutionary_trainer()
        print("  ✓ Learning test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Learning test failed: {e}")
        return False


def test_simulation():
    """Test simulation components"""
    print("Testing simulation...")
    
    try:
        from src.simulation import test_mujoco_env
        test_mujoco_env()
        print("  ✓ Simulation test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Simulation test failed: {e}")
        return False


def test_utils():
    """Test utility components"""
    print("Testing utils...")
    
    try:
        from src.utils.config import test_config_system
        from src.utils.metrics import test_metrics_system
        from src.utils.visualization import test_visualization
        
        test_config_system()
        test_metrics_system()
        test_visualization()
        print("  ✓ Utils test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Utils test failed: {e}")
        return False


def test_evaluation():
    """Test evaluation framework"""
    print("Testing evaluation framework...")
    
    try:
        from src.evaluation import test_evaluation_framework
        test_evaluation_framework()
        print("  ✓ Evaluation test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Evaluation test failed: {e}")
        return False


def test_integration():
    """Test integration between components"""
    print("Testing integration...")
    
    try:
        from src.utils import create_default_config
        from src.dynamics import TVCPlant
        from src.control import LQRController, CLFCBFQPFilter
        import numpy as np
        
        # Create minimal system
        config = create_default_config()
        plant = TVCPlant(config.plant)
        lqr = LQRController(plant, config.lqr)
        safety = CLFCBFQPFilter(plant, lqr, config.safety)
        
        # Test basic operation
        x = np.array([0.1, 0.2])  # Small angle and rate
        reference = np.array([0.0, 0.0])
        
        u_lqr = lqr.control(x, reference)
        u_safe = safety.filter_control(x, u_lqr)
        
        # Check that control outputs are reasonable
        assert abs(u_lqr[0]) < 1.0, "LQR control too large"
        assert abs(u_safe[0]) < 1.0, "Safe control too large"
        
        print("  ✓ Integration test passed")
        return True
        
    except Exception as e:
        print(f"  ✗ Integration test failed: {e}")
        return False


def run_quick_tests():
    """Run only essential quick tests"""
    print("Running quick tests...")
    print("="*40)
    
    tests = [
        ("Imports", test_imports),
        ("Dynamics", test_dynamics),
        ("Control", test_control),
        ("Integration", test_integration)
    ]
    
    results = []
    for name, test_func in tests:
        start_time = time.time()
        success = test_func()
        elapsed = time.time() - start_time
        results.append((name, success, elapsed))
    
    # Summary
    print("\nQuick Test Summary:")
    print("="*40)
    passed = sum(1 for _, success, _ in results if success)
    total = len(results)
    
    for name, success, elapsed in results:
        status = "PASS" if success else "FAIL"
        print(f"{name:12} | {status:4} | {elapsed:.2f}s")
    
    print(f"\nPassed: {passed}/{total}")
    return passed == total


def run_all_tests():
    """Run comprehensive test suite"""
    print("Running comprehensive test suite...")
    print("="*50)
    
    tests = [
        ("Imports", test_imports),
        ("Dynamics", test_dynamics),
        ("Control", test_control),
        ("Learning", test_learning),
        ("Simulation", test_simulation),
        ("Utils", test_utils),
        ("Evaluation", test_evaluation),
        ("Integration", test_integration)
    ]
    
    results = []
    total_time = 0
    
    for name, test_func in tests:
        print(f"\n{'-'*30}")
        print(f"Running {name} tests...")
        print(f"{'-'*30}")
        
        start_time = time.time()
        success = test_func()
        elapsed = time.time() - start_time
        total_time += elapsed
        
        results.append((name, success, elapsed))
    
    # Summary
    print("\n" + "="*50)
    print("COMPREHENSIVE TEST SUMMARY")
    print("="*50)
    
    passed = sum(1 for _, success, _ in results if success)
    total = len(results)
    
    print(f"\nTest Results:")
    for name, success, elapsed in results:
        status = "✓ PASS" if success else "✗ FAIL"
        print(f"  {name:12} | {status:7} | {elapsed:.2f}s")
    
    print(f"\nOverall: {passed}/{total} tests passed")
    print(f"Total time: {total_time:.2f}s")
    
    if passed == total:
        print("\n🎉 All tests passed! System is ready for use.")
    else:
        print(f"\n⚠️  {total - passed} test(s) failed. Check component issues.")
    
    return passed == total


def main():
    """Main test script entry point"""
    parser = argparse.ArgumentParser(description='Test TVC System')
    
    parser.add_argument('--component', type=str, 
                       choices=['dynamics', 'control', 'learning', 'simulation', 'utils', 'evaluation'],
                       help='Test specific component only')
    parser.add_argument('--quick', action='store_true',
                       help='Run only quick essential tests')
    parser.add_argument('--integration', action='store_true',
                       help='Run only integration tests')
    
    args = parser.parse_args()
    
    print("TVC System Test Suite")
    print("="*50)
    
    if args.component:
        # Test specific component
        component_tests = {
            'dynamics': test_dynamics,
            'control': test_control,
            'learning': test_learning,
            'simulation': test_simulation,
            'utils': test_utils,
            'evaluation': test_evaluation
        }
        
        if args.component in component_tests:
            print(f"Testing {args.component} component...")
            success = component_tests[args.component]()
            if success:
                print(f"\n✓ {args.component.title()} component test passed!")
            else:
                print(f"\n✗ {args.component.title()} component test failed!")
                sys.exit(1)
        
    elif args.integration:
        # Test integration only
        success = test_integration()
        if not success:
            sys.exit(1)
    
    elif args.quick:
        # Quick tests
        success = run_quick_tests()
        if not success:
            sys.exit(1)
    
    else:
        # Full test suite
        success = run_all_tests()
        if not success:
            sys.exit(1)
    
    print("\nTest suite completed successfully!")


if __name__ == "__main__":
    main()