#!/usr/bin/env python3
"""
Training script for TVC controllers

This script provides a command-line interface for training different
TVC controllers including neuro-evolution and residual PPO approaches.

Usage:
    python train.py --method evolution --config ../configs/evolution_only.yaml
    python train.py --method ppo --config ../configs/ppo_only.yaml
    python train.py --method all --config ../configs/comparison.yaml

Author: Generated by GitHub Copilot
"""

import argparse
import sys
import time
import numpy as np
from pathlib import Path

# Add src to path - ensure we can find the src directory
script_dir = Path(__file__).parent
project_root = script_dir.parent
src_path = project_root / "src"

if src_path.exists():
    sys.path.insert(0, str(project_root))
else:
    raise ImportError(f"Source directory not found at {src_path}")

from src.dynamics import TVCPlant, TVCParameters
from src.control import MPCController, CLFCBFQPFilter, MPCParameters, SafetyParameters
from src.learning import EvolutionaryTrainer, ResidualPPOTrainer, EvolutionParameters, PPOParameters
import yaml
from typing import Dict, Any, Optional

# Simple config loading utility
def load_yaml_config(config_path: str) -> Dict[str, Any]:
    """Load YAML configuration file with error handling"""
    try:
        config_file = Path(config_path)
        if not config_file.exists():
            # Try relative path from script location
            script_dir = Path(__file__).parent
            relative_config = script_dir / config_path
            if relative_config.exists():
                config_file = relative_config
            else:
                # Try looking in configs directory
                configs_config = script_dir.parent / "configs" / Path(config_path).name
                if configs_config.exists():
                    config_file = configs_config
                else:
                    raise FileNotFoundError(f"Configuration file not found: {config_path}")
        
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)
            
        if not isinstance(config, dict):
            raise ValueError(f"Configuration file must contain a dictionary, got {type(config)}")
            
        print(f"Successfully loaded configuration from: {config_file}")
        return config
        
    except yaml.YAMLError as e:
        raise ValueError(f"Invalid YAML syntax in {config_path}: {e}")
    except Exception as e:
        raise RuntimeError(f"Failed to load configuration from {config_path}: {e}")

# Default configuration fallback
def get_default_config() -> Dict[str, Any]:
    """Get default configuration values"""
    return {
        'experiment_name': 'default_training',
        'output_dir': 'results',
        'use_safety_filter': True,
        'plant': {
            'mass': 1000.0,
            'length': 10.0,
            'inertia': 8333.33,
            'thrust_max': 15000.0,
            'gimbal_limit': 0.2617993877991494,
            'gravity': 9.81,
            'dt': 0.01
        },
        'evolution': {
            'population_size': 200,
            'max_generations': 100,
            'sim_duration': 20.0,
            'mutation_rate': 0.1,
            'elite_ratio': 0.1,
            'tournament_size': 5
        },
        'ppo': {
            'total_frames': 1000000,
            'frames_per_batch': 4096,
            'lr_actor': 0.0003,
            'lr_critic': 0.001,
            'gamma': 0.99,
            'clip_epsilon': 0.2,
            'value_loss_coef': 0.5,
            'entropy_coef': 0.01
        },
        'lqr': {
            'Q': [[100, 0, 0, 0], [0, 100, 0, 0], [0, 0, 10, 0], [0, 0, 0, 10]],
            'R': [[1, 0], [0, 1]]
        },
        'safety': {
            'max_velocity': 50.0,
            'max_angle': 0.785398,
            'barrier_alpha': 1.0,
            'lyapunov_eps': 0.1
        }
    }

class ConfigObject:
    """Simple configuration object with dot notation access"""
    def __init__(self, config_dict: Dict[str, Any]):
        for key, value in config_dict.items():
            if isinstance(value, dict):
                setattr(self, key, ConfigObject(value))
            else:
                setattr(self, key, value)

def create_config_object(config_dict: Dict[str, Any]) -> ConfigObject:
    """Create a configuration object from dictionary"""
    return ConfigObject(config_dict)


def config_to_plant_params(config) -> TVCParameters:
    """Convert config to TVCParameters"""
    plant_config = config.plant
    return TVCParameters(
        mass=plant_config.mass,
        moment_of_inertia=getattr(plant_config, 'moment_of_inertia', getattr(plant_config, 'inertia', 0.1)),
        length=getattr(plant_config, 'length', 1.0),
        nominal_thrust=getattr(plant_config, 'nominal_thrust', getattr(plant_config, 'thrust_max', 15.0)),
        max_thrust=getattr(plant_config, 'max_thrust', getattr(plant_config, 'thrust_max', 20.0)),
        min_thrust=getattr(plant_config, 'min_thrust', 5.0),
        max_gimbal_angle=getattr(plant_config, 'max_gimbal_angle', getattr(plant_config, 'gimbal_limit', np.pi/6)),
        max_gimbal_rate=getattr(plant_config, 'max_gimbal_rate', np.pi),
        gravity=getattr(plant_config, 'gravity', 9.81),
        max_angle=getattr(plant_config, 'max_angle', np.pi/4),
        max_angular_rate=getattr(plant_config, 'max_angular_rate', 2*np.pi),
        disturbance_torque_std=getattr(plant_config, 'disturbance_torque_std', 0.1),
        sensor_noise_std=getattr(plant_config, 'sensor_noise_std', 0.01)
    )


def config_to_evolution_params(config) -> EvolutionParameters:
    """Convert config to EvolutionParameters"""
    evo_config = config.evolution
    plant_dt = getattr(getattr(config, 'plant', None), 'dt', 0.01) if hasattr(config, 'plant') else 0.01
    
    return EvolutionParameters(
        population_size=evo_config.population_size,
        max_generations=evo_config.max_generations,
        sim_duration=evo_config.sim_duration,
        mutation_strength=getattr(evo_config, 'mutation_strength', getattr(evo_config, 'mutation_rate', 0.1)),
        elite_ratio=getattr(evo_config, 'elite_ratio', 0.2),
        mutation_ratio=getattr(evo_config, 'mutation_ratio', 0.6),
        random_ratio=getattr(evo_config, 'random_ratio', 0.2),
        sim_dt=getattr(evo_config, 'sim_dt', plant_dt),
        num_trials=getattr(evo_config, 'num_trials', 3),
        angle_weight=getattr(evo_config, 'angle_weight', 1.0),
        jerk_weight=getattr(evo_config, 'jerk_weight', 0.1),
        safety_penalty=getattr(evo_config, 'safety_penalty', 10.0),
        use_multiprocessing=getattr(evo_config, 'use_multiprocessing', True),
        num_workers=getattr(evo_config, 'num_workers', None)
    )


def config_to_mpc_params(config) -> MPCParameters:
    """Convert config to MPCParameters with legacy LQR support"""
    mpc_config = getattr(config, 'mpc', None)
    # Backward compat: map legacy 'lqr' to MPC fields
    if mpc_config is None and hasattr(config, 'lqr'):
        legacy = config.lqr
        Q = np.array(getattr(legacy, 'Q', [[100.0, 0.0], [0.0, 10.0]]))
        R = getattr(legacy, 'R', 1.0)
        return MPCParameters(Q=Q, R=float(R))
    if mpc_config is None:
        return MPCParameters()
    Q = np.array(getattr(mpc_config, 'Q', [[100.0, 0.0], [0.0, 10.0]]))
    R = float(getattr(mpc_config, 'R', 1.0))
    N = int(getattr(mpc_config, 'N', 20))
    dt = float(getattr(mpc_config, 'dt', 0.01))
    du_rate_limit = bool(getattr(mpc_config, 'du_rate_limit', True))
    warm_start = bool(getattr(mpc_config, 'warm_start', True))
    terminal_lqr = bool(getattr(mpc_config, 'terminal_lqr', True))
    return MPCParameters(Q=Q, R=R, N=N, dt=dt, du_rate_limit=du_rate_limit, warm_start=warm_start, terminal_lqr=terminal_lqr)


def config_to_safety_params(config) -> SafetyParameters:
    """Convert config to SafetyParameters"""
    safety_config = config.safety
    # Map common fields, falling back appropriately
    angle_alpha = getattr(safety_config, 'angle_cbf_alpha', getattr(safety_config, 'barrier_alpha', 2.0))
    rate_alpha = getattr(safety_config, 'rate_cbf_alpha', getattr(safety_config, 'barrier_alpha', 1.5))
    clf_pen = getattr(safety_config, 'clf_penalty', 1000.0)
    return SafetyParameters(
        angle_cbf_alpha=angle_alpha,
        rate_cbf_alpha=rate_alpha,
        clf_penalty=clf_pen,
        qp_eps_abs=getattr(safety_config, 'qp_eps_abs', 1e-4),
        qp_eps_rel=getattr(safety_config, 'qp_eps_rel', 1e-4),
        qp_max_iter=getattr(safety_config, 'qp_max_iter', 1000),
        qp_verbose=getattr(safety_config, 'qp_verbose', False),
        angle_margin_factor=getattr(safety_config, 'angle_margin_factor', 0.9),
        rate_margin_factor=getattr(safety_config, 'rate_margin_factor', 0.9),
    )


def config_to_ppo_params(config) -> PPOParameters:
    """Convert config to PPOParameters"""
    ppo_config = config.ppo
    return PPOParameters(
        total_frames=getattr(ppo_config, 'total_frames', 1_000_000),
        frames_per_batch=getattr(ppo_config, 'frames_per_batch', 2048),
        lr_actor=getattr(ppo_config, 'lr_actor', 3e-4),
        lr_critic=getattr(ppo_config, 'lr_critic', 3e-4),
        gamma=getattr(ppo_config, 'gamma', 0.99),
        clip_epsilon=getattr(ppo_config, 'clip_epsilon', 0.2),
        value_loss_coeff=getattr(ppo_config, 'value_loss_coeff', getattr(ppo_config, 'value_loss_coef', 0.5)),
        entropy_bonus=getattr(ppo_config, 'entropy_bonus', getattr(ppo_config, 'entropy_coef', 0.01)),
        mini_batch_size=getattr(ppo_config, 'mini_batch_size', 64),
        epochs_per_batch=getattr(ppo_config, 'epochs_per_batch', 10),
        max_grad_norm=getattr(ppo_config, 'max_grad_norm', 0.5),
        lr_scheduler_gamma=getattr(ppo_config, 'lr_scheduler_gamma', 0.99),
        lambda_gae=getattr(ppo_config, 'lambda_gae', 0.95),
        max_episode_length=getattr(ppo_config, 'max_episode_length', 500),
        num_envs=getattr(ppo_config, 'num_envs', 1),
        residual_scale=getattr(ppo_config, 'residual_scale', 0.3)
    )


def train_evolution(config_path: Optional[str] = None, save_model: bool = True):
    """Train neuro-evolutionary controller"""
    print("="*60)
    print("TRAINING NEURO-EVOLUTIONARY TVC CONTROLLER")
    print("="*60)
    
    # Load configuration
    if config_path:
        try:
            config_dict = load_yaml_config(config_path)
            config = create_config_object(config_dict)
            print(f"Using configuration: {getattr(config, 'experiment_name', 'unnamed_experiment')}")
        except Exception as e:
            print(f"Error loading configuration: {e}")
            print("Falling back to default configuration...")
            config_dict = get_default_config()
            config_dict['experiment_name'] = "evolution_training"
            config = create_config_object(config_dict)
    else:
        config_dict = get_default_config()
        config_dict['experiment_name'] = "evolution_training"
        config = create_config_object(config_dict)
    print("Using default configuration")
    
    # Convert config to parameter objects
    plant_params = config_to_plant_params(config)
    evo_params = config_to_evolution_params(config)
    
    # Initialize components
    use_safety = bool(getattr(config, 'use_safety_filter', True))
    trainer = EvolutionaryTrainer(plant_params, evo_params, use_safety)
    
    print(f"Population size: {evo_params.population_size}")
    print(f"Max generations: {evo_params.max_generations}")
    print(f"Simulation duration: {evo_params.sim_duration}s")
    print(f"Safety filter: {'enabled' if use_safety else 'disabled'}")
    
    # Train
    start_time = time.time()
    results = trainer.train()
    training_time = time.time() - start_time
    
    print(f"\nTraining completed in {training_time:.2f} seconds")
    print(f"Best fitness: {results['best_fitness']:.6f}")
    print(f"Convergence generation: {results['generations']}")
    
    # Extract results
    best_network = results['best_network']
    training_curves = results['fitness_history']
    
    # Save results
    output_dir = Path(getattr(config, 'output_dir', 'results'))
    output_dir.mkdir(parents=True, exist_ok=True)
    
    if save_model:
        import torch
        model_path = output_dir / "evolution_controller.pth"
        torch.save(best_network.state_dict(), model_path)
        print(f"Model saved to {model_path}")
    
    # Save training curves
    import json
    import numpy as np
    
    # Convert numpy arrays to lists for JSON serialization
    curves_for_json = {}
    for key, value in training_curves.items():
        if isinstance(value, np.ndarray):
            curves_for_json[key] = value.tolist()
        elif isinstance(value, list):
            curves_for_json[key] = [float(x) if isinstance(x, (np.floating, np.integer)) else x for x in value]
        else:
            curves_for_json[key] = value
    
    curves_path = output_dir / "evolution_training_curves.json"
    with open(curves_path, 'w') as f:
        json.dump(curves_for_json, f, indent=2)
    print(f"Training curves saved to {curves_path}")
    
    return best_network, training_curves


def train_ppo(config_path: Optional[str] = None, save_model: bool = True):
    """Train residual PPO controller"""
    print("="*60)
    print("TRAINING RESIDUAL PPO TVC CONTROLLER")
    print("="*60)
    
    # Load configuration
    if config_path:
        try:
            config_dict = load_yaml_config(config_path)
            config = create_config_object(config_dict)
            print(f"Using configuration: {getattr(config, 'experiment_name', 'unnamed_experiment')}")
        except Exception as e:
            print(f"Error loading configuration: {e}")
            print("Falling back to default configuration...")
            config_dict = get_default_config()
            config_dict['experiment_name'] = "ppo_training"
            config = create_config_object(config_dict)
    else:
        config_dict = get_default_config()
        config_dict['experiment_name'] = "ppo_training"
        config = create_config_object(config_dict)
        print("Using default configuration")
    
    # Convert config to parameter objects
    plant_params = config_to_plant_params(config)
    ppo_params = config_to_ppo_params(config)
    
    # Initialize components
    use_safety = bool(getattr(config, 'use_safety_filter', True))
    trainer = ResidualPPOTrainer(plant_params, ppo_params, use_safety)
    
    print(f"Total frames: {ppo_params.total_frames:,}")
    print(f"Frames per batch: {ppo_params.frames_per_batch:,}")
    print(f"Learning rates: actor={ppo_params.lr_actor}, critic={ppo_params.lr_critic}")
    print(f"Safety filter: {'enabled' if use_safety else 'disabled'}")
    
    # Train
    start_time = time.time()
    results = trainer.train()
    training_time = results['training_time']
    
    print(f"\nTraining completed in {training_time:.2f} seconds")
    ep_rewards = results['training_stats']['episode_rewards']
    final_reward = float(np.mean(ep_rewards[-10:])) if ep_rewards else 0.0
    print(f"Final mean reward (last 10): {final_reward:.6f}")
    print(f"Total frames: {results['total_frames']:,}")
    
    # Save results
    output_dir = Path(getattr(config, 'output_dir', 'results'))
    output_dir.mkdir(parents=True, exist_ok=True)
    
    if save_model:
        import torch
        model_path = output_dir / "ppo_controller.pth"
        torch.save(results['actor'].state_dict(), model_path)
        print(f"Model saved to {model_path}")
    
    # Save training curves
    import json
    curves_path = output_dir / "ppo_training_stats.json"
    with open(curves_path, 'w') as f:
        json.dump(results['training_stats'], f, indent=2)
    print(f"Training curves saved to {curves_path}")
    
    return results['actor'], results['training_stats']


def train_all(config_path: Optional[str] = None):
    """Train all controller types"""
    print("="*60)
    print("TRAINING ALL TVC CONTROLLERS")
    print("="*60)
    
    # Load configuration
    if config_path:
        try:
            config_dict = load_yaml_config(config_path)
            config = create_config_object(config_dict)
            print(f"Using configuration: {getattr(config, 'experiment_name', 'unnamed_experiment')}")
        except Exception as e:
            print(f"Error loading configuration: {e}")
            print("Falling back to default configuration...")
            config_dict = get_default_config()
            config_dict['experiment_name'] = "all_controllers_training"
            config = create_config_object(config_dict)
    else:
        config_dict = get_default_config()
        config_dict['experiment_name'] = "all_controllers_training"
        config = create_config_object(config_dict)
        print("Using default configuration")
    
    all_results = {}
    
    # 1. Train Evolution
    print("\n" + "="*40)
    print("1. TRAINING NEURO-EVOLUTION")
    print("="*40)
    
    try:
        evolution_net, evolution_curves = train_evolution(config_path, save_model=True)
        all_results['evolution'] = {
            'network': evolution_net,
            'curves': evolution_curves,
            'status': 'success'
        }
    except Exception as e:
        print(f"Evolution training failed: {e}")
        all_results['evolution'] = {'status': 'failed', 'error': str(e)}
    
    # 2. Train PPO
    print("\n" + "="*40)
    print("2. TRAINING RESIDUAL PPO")
    print("="*40)
    
    try:
        ppo_policy, ppo_curves = train_ppo(config_path, save_model=True)
        all_results['ppo'] = {
            'policy': ppo_policy,
            'curves': ppo_curves,
            'status': 'success'
        }
    except Exception as e:
        print(f"PPO training failed: {e}")
        all_results['ppo'] = {'status': 'failed', 'error': str(e)}
    
    # Summary
    print("\n" + "="*60)
    print("TRAINING SUMMARY")
    print("="*60)
    
    for method, results in all_results.items():
        status = results['status']
        print(f"{method.upper()}: {status}")
        if status == 'failed':
            print(f"  Error: {results['error']}")
        elif status == 'success':
            print(f"  ✓ Training completed successfully")
    
    return all_results


def list_available_configs():
    """List all available configuration files"""
    configs_dir = Path(__file__).parent.parent / "configs"
    
    if configs_dir.exists():
        print("Available configuration files:")
        print("="*50)
        yaml_files = list(configs_dir.glob("*.yaml"))
        
        if yaml_files:
            for config_file in sorted(yaml_files):
                print(f"  {config_file.name}")
                
                # Try to load and show brief description
                try:
                    with open(config_file, 'r') as f:
                        config = yaml.safe_load(f)
                        if isinstance(config, dict) and 'description' in config:
                            print(f"    Description: {config['description']}")
                        elif isinstance(config, dict) and 'experiment_name' in config:
                            print(f"    Experiment: {config['experiment_name']}")
                        print()
                except Exception:
                    print()
                    
            print(f"Usage: python train.py --method <method> --config ../configs/<config_name>.yaml")
        else:
            print("  No configuration files found")
    else:
        print(f"Configuration directory not found: {configs_dir}")
        print("Please ensure you're running from the scripts/ directory.")


def create_example_configs():
    """Create example configuration files"""
    configs_dir = Path(__file__).parent.parent / "configs"
    
    if configs_dir.exists():
        print(f"Configuration files already exist in {configs_dir}/")
        print("Use --list-configs to see available configurations")
    else:
        print(f"Configuration directory not found: {configs_dir}")
        print("Please run the script from the project root directory.")


def main():
    """Main training script entry point"""
    parser = argparse.ArgumentParser(description='Train TVC Controllers')
    
    parser.add_argument('--method', type=str, choices=['evolution', 'ppo', 'all'],
                       default='evolution', help='Training method to use')
    parser.add_argument('--config', type=str, help='Path to configuration file (e.g., ../configs/default.yaml)')
    parser.add_argument('--create-configs', action='store_true', 
                       help='List available configuration files')
    parser.add_argument('--list-configs', action='store_true',
                       help='List available configuration files')
    parser.add_argument('--no-save', action='store_true',
                       help='Do not save trained models')
    
    args = parser.parse_args()
    
    # List available configs if requested
    if args.list_configs:
        list_available_configs()
        return
    
    # Create example configs if requested
    if args.create_configs:
        create_example_configs()
        return
    
    # Training
    save_model = not args.no_save
    
    if args.method == 'evolution':
        train_evolution(args.config, save_model)
    elif args.method == 'ppo':
        train_ppo(args.config, save_model)
    elif args.method == 'all':
        train_all(args.config)
    
    print("\nTraining script completed!")


if __name__ == "__main__":
    main()